apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ambient-project-admin-clusterrole.yaml
- ambient-project-edit-clusterrole.yaml
- ambient-project-view-clusterrole.yaml
- ambient-users-list-projects-clusterrolebinding.yaml
- control-plane-sa.yaml
- control-plane-clusterrole.yaml
- control-plane-clusterrolebinding.yaml
