// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: c0552a0db4fdb51e6e5cf28c453ea87920416eaa69cdca8a78e6063c513b7bab
// Generated: 2026-07-20T04:51:09Z

package types

import (
	"errors"
	"fmt"
	"time"
)

type Cluster struct {
	ObjectReference

	Annotations     string     `json:"annotations,omitempty"`
	APIServerURL    string     `json:"api_server_url"`
	Capacity        string     `json:"capacity,omitempty"`
	CredentialID    string     `json:"credential_id,omitempty"`
	Description     string     `json:"description,omitempty"`
	Labels          string     `json:"labels,omitempty"`
	LastHeartbeatAt *time.Time `json:"last_heartbeat_at,omitempty"`
	Name            string     `json:"name"`
	Role            string     `json:"role"`
	Status          string     `json:"status,omitempty"`
	StatusMessage   string     `json:"status_message,omitempty"`
}

type ClusterList struct {
	ListMeta
	Items []Cluster `json:"items"`
}

func (l *ClusterList) GetItems() []Cluster { return l.Items }
func (l *ClusterList) GetTotal() int       { return l.Total }
func (l *ClusterList) GetPage() int        { return l.Page }
func (l *ClusterList) GetSize() int        { return l.Size }

type ClusterBuilder struct {
	resource Cluster
	errors   []error
}

func NewClusterBuilder() *ClusterBuilder {
	return &ClusterBuilder{}
}

func (b *ClusterBuilder) Annotations(v string) *ClusterBuilder {
	b.resource.Annotations = v
	return b
}

func (b *ClusterBuilder) APIServerURL(v string) *ClusterBuilder {
	b.resource.APIServerURL = v
	return b
}

func (b *ClusterBuilder) CredentialID(v string) *ClusterBuilder {
	b.resource.CredentialID = v
	return b
}

func (b *ClusterBuilder) Description(v string) *ClusterBuilder {
	b.resource.Description = v
	return b
}

func (b *ClusterBuilder) Labels(v string) *ClusterBuilder {
	b.resource.Labels = v
	return b
}

func (b *ClusterBuilder) Name(v string) *ClusterBuilder {
	b.resource.Name = v
	return b
}

func (b *ClusterBuilder) Role(v string) *ClusterBuilder {
	b.resource.Role = v
	return b
}

func (b *ClusterBuilder) Build() (*Cluster, error) {
	if b.resource.APIServerURL == "" {
		b.errors = append(b.errors, fmt.Errorf("api_server_url is required"))
	}
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if b.resource.Role == "" {
		b.errors = append(b.errors, fmt.Errorf("role is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type ClusterPatchBuilder struct {
	patch map[string]any
}

func NewClusterPatchBuilder() *ClusterPatchBuilder {
	return &ClusterPatchBuilder{patch: make(map[string]any)}
}

func (b *ClusterPatchBuilder) Annotations(v string) *ClusterPatchBuilder {
	b.patch["annotations"] = v
	return b
}

func (b *ClusterPatchBuilder) APIServerURL(v string) *ClusterPatchBuilder {
	b.patch["api_server_url"] = v
	return b
}

func (b *ClusterPatchBuilder) CredentialID(v string) *ClusterPatchBuilder {
	b.patch["credential_id"] = v
	return b
}

func (b *ClusterPatchBuilder) Description(v string) *ClusterPatchBuilder {
	b.patch["description"] = v
	return b
}

func (b *ClusterPatchBuilder) Labels(v string) *ClusterPatchBuilder {
	b.patch["labels"] = v
	return b
}

func (b *ClusterPatchBuilder) Name(v string) *ClusterPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *ClusterPatchBuilder) Role(v string) *ClusterPatchBuilder {
	b.patch["role"] = v
	return b
}

func (b *ClusterPatchBuilder) Build() map[string]any {
	return b.patch
}

type ClusterStatusResponse struct {
	Capacity        string     `json:"capacity,omitempty"`
	ID              string     `json:"id,omitempty"`
	LastHeartbeatAt *time.Time `json:"last_heartbeat_at,omitempty"`
	Status          string     `json:"status,omitempty"`
	StatusMessage   string     `json:"status_message,omitempty"`
}
