// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: c9d4494778eb0a006db1f289630460fb9b5dc58df1895903c42735b4f56b0314
// Generated: 2026-05-05T18:24:54Z

package types

import (
	"errors"
	"fmt"
)

type RoleBinding struct {
	ObjectReference

	RoleID  string `json:"role_id"`
	Scope   string `json:"scope"`
	ScopeID string `json:"scope_id,omitempty"`
	UserID  string `json:"user_id"`
}

type RoleBindingList struct {
	ListMeta
	Items []RoleBinding `json:"items"`
}

func (l *RoleBindingList) GetItems() []RoleBinding { return l.Items }
func (l *RoleBindingList) GetTotal() int           { return l.Total }
func (l *RoleBindingList) GetPage() int            { return l.Page }
func (l *RoleBindingList) GetSize() int            { return l.Size }

type RoleBindingBuilder struct {
	resource RoleBinding
	errors   []error
}

func NewRoleBindingBuilder() *RoleBindingBuilder {
	return &RoleBindingBuilder{}
}

func (b *RoleBindingBuilder) RoleID(v string) *RoleBindingBuilder {
	b.resource.RoleID = v
	return b
}

func (b *RoleBindingBuilder) Scope(v string) *RoleBindingBuilder {
	b.resource.Scope = v
	return b
}

func (b *RoleBindingBuilder) ScopeID(v string) *RoleBindingBuilder {
	b.resource.ScopeID = v
	return b
}

func (b *RoleBindingBuilder) UserID(v string) *RoleBindingBuilder {
	b.resource.UserID = v
	return b
}

func (b *RoleBindingBuilder) Build() (*RoleBinding, error) {
	if b.resource.RoleID == "" {
		b.errors = append(b.errors, fmt.Errorf("role_id is required"))
	}
	if b.resource.Scope == "" {
		b.errors = append(b.errors, fmt.Errorf("scope is required"))
	}
	if b.resource.UserID == "" {
		b.errors = append(b.errors, fmt.Errorf("user_id is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type RoleBindingPatchBuilder struct {
	patch map[string]any
}

func NewRoleBindingPatchBuilder() *RoleBindingPatchBuilder {
	return &RoleBindingPatchBuilder{patch: make(map[string]any)}
}

func (b *RoleBindingPatchBuilder) RoleID(v string) *RoleBindingPatchBuilder {
	b.patch["role_id"] = v
	return b
}

func (b *RoleBindingPatchBuilder) Scope(v string) *RoleBindingPatchBuilder {
	b.patch["scope"] = v
	return b
}

func (b *RoleBindingPatchBuilder) ScopeID(v string) *RoleBindingPatchBuilder {
	b.patch["scope_id"] = v
	return b
}

func (b *RoleBindingPatchBuilder) UserID(v string) *RoleBindingPatchBuilder {
	b.patch["user_id"] = v
	return b
}

func (b *RoleBindingPatchBuilder) Build() map[string]any {
	return b.patch
}
