// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: da9fbb26cd926e7df1af31ad78f47d005fd328228df521e9e3411636e5069455
// Generated: 2026-05-13T23:03:22Z

package types

import (
	"errors"
	"fmt"
)

type RoleBinding struct {
	ObjectReference

	AgentID      *string `json:"agent_id,omitempty"`
	CredentialID *string `json:"credential_id,omitempty"`
	ProjectID    *string `json:"project_id,omitempty"`
	RoleID       string  `json:"role_id"`
	Scope        string  `json:"scope"`
	SessionID    *string `json:"session_id,omitempty"`
	UserID       *string `json:"user_id,omitempty"`
}

type RoleBindingList struct {
	ListMeta
	Items []RoleBinding `json:"items"`
}

func (l *RoleBindingList) GetItems() []RoleBinding { return l.Items }
func (l *RoleBindingList) GetTotal() int           { return l.Total }
func (l *RoleBindingList) GetPage() int            { return l.Page }
func (l *RoleBindingList) GetSize() int            { return l.Size }

type RoleBindingBuilder struct {
	resource RoleBinding
	errors   []error
}

func NewRoleBindingBuilder() *RoleBindingBuilder {
	return &RoleBindingBuilder{}
}

func (b *RoleBindingBuilder) AgentID(v string) *RoleBindingBuilder {
	b.resource.AgentID = &v
	return b
}

func (b *RoleBindingBuilder) CredentialID(v string) *RoleBindingBuilder {
	b.resource.CredentialID = &v
	return b
}

func (b *RoleBindingBuilder) ProjectID(v string) *RoleBindingBuilder {
	b.resource.ProjectID = &v
	return b
}

func (b *RoleBindingBuilder) RoleID(v string) *RoleBindingBuilder {
	b.resource.RoleID = v
	return b
}

func (b *RoleBindingBuilder) Scope(v string) *RoleBindingBuilder {
	b.resource.Scope = v
	return b
}

func (b *RoleBindingBuilder) SessionID(v string) *RoleBindingBuilder {
	b.resource.SessionID = &v
	return b
}

func (b *RoleBindingBuilder) UserID(v string) *RoleBindingBuilder {
	b.resource.UserID = &v
	return b
}

func (b *RoleBindingBuilder) Build() (*RoleBinding, error) {
	if b.resource.RoleID == "" {
		b.errors = append(b.errors, fmt.Errorf("role_id is required"))
	}
	if b.resource.Scope == "" {
		b.errors = append(b.errors, fmt.Errorf("scope is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type RoleBindingPatchBuilder struct {
	patch map[string]any
}

func NewRoleBindingPatchBuilder() *RoleBindingPatchBuilder {
	return &RoleBindingPatchBuilder{patch: make(map[string]any)}
}

func (b *RoleBindingPatchBuilder) AgentID(v *string) *RoleBindingPatchBuilder {
	b.patch["agent_id"] = v
	return b
}

func (b *RoleBindingPatchBuilder) CredentialID(v *string) *RoleBindingPatchBuilder {
	b.patch["credential_id"] = v
	return b
}

func (b *RoleBindingPatchBuilder) ProjectID(v *string) *RoleBindingPatchBuilder {
	b.patch["project_id"] = v
	return b
}

func (b *RoleBindingPatchBuilder) RoleID(v string) *RoleBindingPatchBuilder {
	b.patch["role_id"] = v
	return b
}

func (b *RoleBindingPatchBuilder) Scope(v string) *RoleBindingPatchBuilder {
	b.patch["scope"] = v
	return b
}

func (b *RoleBindingPatchBuilder) SessionID(v *string) *RoleBindingPatchBuilder {
	b.patch["session_id"] = v
	return b
}

func (b *RoleBindingPatchBuilder) UserID(v *string) *RoleBindingPatchBuilder {
	b.patch["user_id"] = v
	return b
}

func (b *RoleBindingPatchBuilder) Build() map[string]any {
	return b.patch
}
