// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 84c6a5120d178ae5bb13cd53f756c9ec09c9127f381cf380f9bfc8f8d5de4412
// Generated: 2026-07-15T03:32:32Z

package types

import (
	"errors"
	"fmt"
	"time"
)

type Session struct {
	ObjectReference

	AgentID                  string     `json:"agent_id,omitempty"`
	Annotations              string     `json:"annotations,omitempty"`
	AssignedUserID           string     `json:"assigned_user_id,omitempty"`
	BotAccountName           string     `json:"bot_account_name,omitempty"`
	CompletionTime           *time.Time `json:"completion_time,omitempty"`
	Conditions               string     `json:"conditions,omitempty"`
	CreatedByUserID          string     `json:"created_by_user_id,omitempty"`
	EnvironmentVariables     string     `json:"environment_variables,omitempty"`
	KubeCrName               string     `json:"kube_cr_name,omitempty"`
	KubeCrUid                string     `json:"kube_cr_uid,omitempty"`
	KubeNamespace            string     `json:"kube_namespace,omitempty"`
	Labels                   string     `json:"labels,omitempty"`
	LastActivityAt           *time.Time `json:"last_activity_at,omitempty"`
	LlmMaxTokens             int        `json:"llm_max_tokens,omitempty"`
	LlmModel                 string     `json:"llm_model,omitempty"`
	LlmTemperature           float64    `json:"llm_temperature,omitempty"`
	Name                     string     `json:"name"`
	ParentSessionID          string     `json:"parent_session_id,omitempty"`
	Phase                    string     `json:"phase,omitempty"`
	ProjectID                string     `json:"project_id,omitempty"`
	Prompt                   string     `json:"prompt,omitempty"`
	ReconciledRepos          string     `json:"reconciled_repos,omitempty"`
	ReconciledWorkflow       string     `json:"reconciled_workflow,omitempty"`
	RepoURL                  string     `json:"repo_url,omitempty"`
	Repos                    string     `json:"repos,omitempty"`
	ResourceOverrides        string     `json:"resource_overrides,omitempty"`
	SandboxLogsSnapshot      string     `json:"sandbox_logs_snapshot,omitempty"`
	SandboxPolicySnapshot    string     `json:"sandbox_policy_snapshot,omitempty"`
	ScheduledFor             *time.Time `json:"scheduled_for,omitempty"`
	SdkRestartCount          int        `json:"sdk_restart_count,omitempty"`
	SdkSessionID             string     `json:"sdk_session_id,omitempty"`
	SourceScheduledSessionID string     `json:"source_scheduled_session_id,omitempty"`
	StartTime                *time.Time `json:"start_time,omitempty"`
	Timeout                  int        `json:"timeout,omitempty"`
	WorkflowID               string     `json:"workflow_id,omitempty"`
}

type SessionList struct {
	ListMeta
	Items []Session `json:"items"`
}

func (l *SessionList) GetItems() []Session { return l.Items }
func (l *SessionList) GetTotal() int       { return l.Total }
func (l *SessionList) GetPage() int        { return l.Page }
func (l *SessionList) GetSize() int        { return l.Size }

type SessionBuilder struct {
	resource Session
	errors   []error
}

func NewSessionBuilder() *SessionBuilder {
	return &SessionBuilder{}
}

func (b *SessionBuilder) AgentID(v string) *SessionBuilder {
	b.resource.AgentID = v
	return b
}

func (b *SessionBuilder) Annotations(v string) *SessionBuilder {
	b.resource.Annotations = v
	return b
}

func (b *SessionBuilder) AssignedUserID(v string) *SessionBuilder {
	b.resource.AssignedUserID = v
	return b
}

func (b *SessionBuilder) BotAccountName(v string) *SessionBuilder {
	b.resource.BotAccountName = v
	return b
}

func (b *SessionBuilder) EnvironmentVariables(v string) *SessionBuilder {
	b.resource.EnvironmentVariables = v
	return b
}

func (b *SessionBuilder) Labels(v string) *SessionBuilder {
	b.resource.Labels = v
	return b
}

func (b *SessionBuilder) LlmMaxTokens(v int) *SessionBuilder {
	b.resource.LlmMaxTokens = v
	return b
}

func (b *SessionBuilder) LlmModel(v string) *SessionBuilder {
	b.resource.LlmModel = v
	return b
}

func (b *SessionBuilder) LlmTemperature(v float64) *SessionBuilder {
	b.resource.LlmTemperature = v
	return b
}

func (b *SessionBuilder) Name(v string) *SessionBuilder {
	b.resource.Name = v
	return b
}

func (b *SessionBuilder) ParentSessionID(v string) *SessionBuilder {
	b.resource.ParentSessionID = v
	return b
}

func (b *SessionBuilder) ProjectID(v string) *SessionBuilder {
	b.resource.ProjectID = v
	return b
}

func (b *SessionBuilder) Prompt(v string) *SessionBuilder {
	b.resource.Prompt = v
	return b
}

func (b *SessionBuilder) RepoURL(v string) *SessionBuilder {
	b.resource.RepoURL = v
	return b
}

func (b *SessionBuilder) Repos(v string) *SessionBuilder {
	b.resource.Repos = v
	return b
}

func (b *SessionBuilder) ResourceOverrides(v string) *SessionBuilder {
	b.resource.ResourceOverrides = v
	return b
}

func (b *SessionBuilder) Timeout(v int) *SessionBuilder {
	b.resource.Timeout = v
	return b
}

func (b *SessionBuilder) WorkflowID(v string) *SessionBuilder {
	b.resource.WorkflowID = v
	return b
}

func (b *SessionBuilder) Build() (*Session, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type SessionPatchBuilder struct {
	patch map[string]any
}

func NewSessionPatchBuilder() *SessionPatchBuilder {
	return &SessionPatchBuilder{patch: make(map[string]any)}
}

func (b *SessionPatchBuilder) Annotations(v string) *SessionPatchBuilder {
	b.patch["annotations"] = v
	return b
}

func (b *SessionPatchBuilder) AssignedUserID(v string) *SessionPatchBuilder {
	b.patch["assigned_user_id"] = v
	return b
}

func (b *SessionPatchBuilder) BotAccountName(v string) *SessionPatchBuilder {
	b.patch["bot_account_name"] = v
	return b
}

func (b *SessionPatchBuilder) EnvironmentVariables(v string) *SessionPatchBuilder {
	b.patch["environment_variables"] = v
	return b
}

func (b *SessionPatchBuilder) Labels(v string) *SessionPatchBuilder {
	b.patch["labels"] = v
	return b
}

func (b *SessionPatchBuilder) LlmMaxTokens(v int) *SessionPatchBuilder {
	b.patch["llm_max_tokens"] = v
	return b
}

func (b *SessionPatchBuilder) LlmModel(v string) *SessionPatchBuilder {
	b.patch["llm_model"] = v
	return b
}

func (b *SessionPatchBuilder) LlmTemperature(v float64) *SessionPatchBuilder {
	b.patch["llm_temperature"] = v
	return b
}

func (b *SessionPatchBuilder) Name(v string) *SessionPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *SessionPatchBuilder) ParentSessionID(v string) *SessionPatchBuilder {
	b.patch["parent_session_id"] = v
	return b
}

func (b *SessionPatchBuilder) Prompt(v string) *SessionPatchBuilder {
	b.patch["prompt"] = v
	return b
}

func (b *SessionPatchBuilder) RepoURL(v string) *SessionPatchBuilder {
	b.patch["repo_url"] = v
	return b
}

func (b *SessionPatchBuilder) Repos(v string) *SessionPatchBuilder {
	b.patch["repos"] = v
	return b
}

func (b *SessionPatchBuilder) ResourceOverrides(v string) *SessionPatchBuilder {
	b.patch["resource_overrides"] = v
	return b
}

func (b *SessionPatchBuilder) Timeout(v int) *SessionPatchBuilder {
	b.patch["timeout"] = v
	return b
}

func (b *SessionPatchBuilder) WorkflowID(v string) *SessionPatchBuilder {
	b.patch["workflow_id"] = v
	return b
}

func (b *SessionPatchBuilder) Build() map[string]any {
	return b.patch
}

type SessionStatusPatchBuilder struct {
	patch map[string]any
}

func NewSessionStatusPatchBuilder() *SessionStatusPatchBuilder {
	return &SessionStatusPatchBuilder{patch: make(map[string]any)}
}

func (b *SessionStatusPatchBuilder) CompletionTime(v *time.Time) *SessionStatusPatchBuilder {
	b.patch["completion_time"] = v
	return b
}

func (b *SessionStatusPatchBuilder) Conditions(v string) *SessionStatusPatchBuilder {
	b.patch["conditions"] = v
	return b
}

func (b *SessionStatusPatchBuilder) KubeCrUid(v string) *SessionStatusPatchBuilder {
	b.patch["kube_cr_uid"] = v
	return b
}

func (b *SessionStatusPatchBuilder) KubeNamespace(v string) *SessionStatusPatchBuilder {
	b.patch["kube_namespace"] = v
	return b
}

func (b *SessionStatusPatchBuilder) Phase(v string) *SessionStatusPatchBuilder {
	b.patch["phase"] = v
	return b
}

func (b *SessionStatusPatchBuilder) ReconciledRepos(v string) *SessionStatusPatchBuilder {
	b.patch["reconciled_repos"] = v
	return b
}

func (b *SessionStatusPatchBuilder) ReconciledWorkflow(v string) *SessionStatusPatchBuilder {
	b.patch["reconciled_workflow"] = v
	return b
}

func (b *SessionStatusPatchBuilder) SandboxLogsSnapshot(v string) *SessionStatusPatchBuilder {
	b.patch["sandbox_logs_snapshot"] = v
	return b
}

func (b *SessionStatusPatchBuilder) SandboxPolicySnapshot(v string) *SessionStatusPatchBuilder {
	b.patch["sandbox_policy_snapshot"] = v
	return b
}

func (b *SessionStatusPatchBuilder) SdkRestartCount(v int) *SessionStatusPatchBuilder {
	b.patch["sdk_restart_count"] = v
	return b
}

func (b *SessionStatusPatchBuilder) SdkSessionID(v string) *SessionStatusPatchBuilder {
	b.patch["sdk_session_id"] = v
	return b
}

func (b *SessionStatusPatchBuilder) StartTime(v *time.Time) *SessionStatusPatchBuilder {
	b.patch["start_time"] = v
	return b
}

func (b *SessionStatusPatchBuilder) Build() map[string]any {
	return b.patch
}
