// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 84c6a5120d178ae5bb13cd53f756c9ec09c9127f381cf380f9bfc8f8d5de4412
// Generated: 2026-07-15T03:32:32Z

package types

import (
	"errors"
	"fmt"
)

type User struct {
	ObjectReference

	Email    string `json:"email,omitempty"`
	Name     string `json:"name"`
	Username string `json:"username"`
}

type UserList struct {
	ListMeta
	Items []User `json:"items"`
}

func (l *UserList) GetItems() []User { return l.Items }
func (l *UserList) GetTotal() int    { return l.Total }
func (l *UserList) GetPage() int     { return l.Page }
func (l *UserList) GetSize() int     { return l.Size }

type UserBuilder struct {
	resource User
	errors   []error
}

func NewUserBuilder() *UserBuilder {
	return &UserBuilder{}
}

func (b *UserBuilder) Email(v string) *UserBuilder {
	b.resource.Email = v
	return b
}

func (b *UserBuilder) Name(v string) *UserBuilder {
	b.resource.Name = v
	return b
}

func (b *UserBuilder) Username(v string) *UserBuilder {
	b.resource.Username = v
	return b
}

func (b *UserBuilder) Build() (*User, error) {
	if b.resource.Name == "" {
		b.errors = append(b.errors, fmt.Errorf("name is required"))
	}
	if b.resource.Username == "" {
		b.errors = append(b.errors, fmt.Errorf("username is required"))
	}
	if len(b.errors) > 0 {
		return nil, fmt.Errorf("validation failed: %w", errors.Join(b.errors...))
	}
	return &b.resource, nil
}

type UserPatchBuilder struct {
	patch map[string]any
}

func NewUserPatchBuilder() *UserPatchBuilder {
	return &UserPatchBuilder{patch: make(map[string]any)}
}

func (b *UserPatchBuilder) Email(v string) *UserPatchBuilder {
	b.patch["email"] = v
	return b
}

func (b *UserPatchBuilder) Name(v string) *UserPatchBuilder {
	b.patch["name"] = v
	return b
}

func (b *UserPatchBuilder) Username(v string) *UserPatchBuilder {
	b.patch["username"] = v
	return b
}

func (b *UserPatchBuilder) Build() map[string]any {
	return b.patch
}
