kind: Kustomization
resources:
  - agents/hello-world.yaml
  - agents/security-reviewer.yaml
  - agents/jira-simple-whoami.yaml
  - agents/pr-reviewer.yaml
  - agents/jira-issue-categorizer.yaml
  - providers/vertex.yaml
  - providers/github.yaml
  - providers/jira.yaml
