apiVersion: v1
kind: Service
metadata:
  name: ambient-ui-service
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: ambient-ui-proxy-tls
spec:
  ports:
  - port: 8443
    targetPort: oauthproxy
    protocol: TCP
    name: oauthproxy
