# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 84c6a5120d178ae5bb13cd53f756c9ec09c9127f381cf380f9bfc8f8d5de4412
# Generated: 2026-07-15T03:32:32Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING

from ._base import ListOptions
from .application import Application, ApplicationList

if TYPE_CHECKING:
    from .client import AmbientClient


class ApplicationAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client

    def create(self, data: dict) -> Application:
        resp = self._client._request("POST", "/applications", json=data)
        return Application.from_dict(resp)

    def get(self, resource_id: str) -> Application:
        resp = self._client._request("GET", f"/applications/{resource_id}")
        return Application.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> ApplicationList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", "/applications", params=params)
        return ApplicationList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> Application:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"/applications/{resource_id}", json=data)
        return Application.from_dict(resp)

    def delete(self, resource_id: str) -> None:
        self._client._request("DELETE", f"/applications/{resource_id}", expect_json=False)

    def refresh(self, resource_id: str) -> Application:
        resp = self._client._request("POST", f"/applications/{resource_id}/refresh")
        return Application.from_dict(resp)

    def sync(self, resource_id: str) -> Application:
        resp = self._client._request("POST", f"/applications/{resource_id}/sync")
        return Application.from_dict(resp)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[Application]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
