# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: c9d4494778eb0a006db1f289630460fb9b5dc58df1895903c42735b4f56b0314
# Generated: 2026-05-05T18:24:54Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING
from urllib.parse import quote

from ._base import ListOptions
from .credential import Credential, CredentialList

if TYPE_CHECKING:
    from .client import AmbientClient


class CredentialAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client
    def _base_path(self) -> str:
        return "/projects/{id}/credentials".replace("{id}", quote(self._client._project, safe=""))


    def create(self, data: dict) -> Credential:
        resp = self._client._request("POST", self._base_path(), json=data)
        return Credential.from_dict(resp)

    def get(self, resource_id: str) -> Credential:
        resp = self._client._request("GET", f"{self._base_path()}/{resource_id}")
        return Credential.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> CredentialList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", self._base_path(), params=params)
        return CredentialList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> Credential:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"{self._base_path()}/{resource_id}", json=data)
        return Credential.from_dict(resp)

    def delete(self, resource_id: str) -> None:
        self._client._request("DELETE", f"{self._base_path()}/{resource_id}", expect_json=False)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[Credential]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
