# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: bef3ff7d01cca0bab82f7c3ab91c59e2aceaf2971b9a3a784292ce7d47faa67f
# Generated: 2026-07-19T01:32:48Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING
from urllib.parse import quote

from ._base import ListOptions
from .gateway import Gateway, GatewayList

if TYPE_CHECKING:
    from .client import AmbientClient


class GatewayAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client
    def _base_path(self) -> str:
        return "/projects/{id}/gateways".replace("{id}", quote(self._client._project, safe=""))


    def create(self, data: dict) -> Gateway:
        resp = self._client._request("POST", self._base_path(), json=data)
        return Gateway.from_dict(resp)

    def get(self, resource_id: str) -> Gateway:
        resp = self._client._request("GET", f"{self._base_path()}/{resource_id}")
        return Gateway.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> GatewayList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", self._base_path(), params=params)
        return GatewayList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> Gateway:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"{self._base_path()}/{resource_id}", json=data)
        return Gateway.from_dict(resp)

    def delete(self, resource_id: str) -> None:
        self._client._request("DELETE", f"{self._base_path()}/{resource_id}", expect_json=False)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[Gateway]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
