# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 0d99d538cf2137af9c98c3b852de4b2c46377626d7f163abfb3af9423cad7afa
# Generated: 2026-07-08T01:48:22Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING
from urllib.parse import quote

from ._base import ListOptions
from .policy import Policy, PolicyList

if TYPE_CHECKING:
    from .client import AmbientClient


class PolicyAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client
    def _base_path(self) -> str:
        return "/projects/{id}/policies".replace("{id}", quote(self._client._project, safe=""))


    def create(self, data: dict) -> Policy:
        resp = self._client._request("POST", self._base_path(), json=data)
        return Policy.from_dict(resp)

    def get(self, resource_id: str) -> Policy:
        resp = self._client._request("GET", f"{self._base_path()}/{resource_id}")
        return Policy.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> PolicyList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", self._base_path(), params=params)
        return PolicyList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> Policy:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"{self._base_path()}/{resource_id}", json=data)
        return Policy.from_dict(resp)

    def delete(self, resource_id: str) -> None:
        self._client._request("DELETE", f"{self._base_path()}/{resource_id}", expect_json=False)

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[Policy]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
