# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: a45fc06b261cd394c9ceb9817484b3742fa24f7acf8e2adaeb15ea4ec80ec86b
# Generated: 2026-06-17T18:27:02Z

from __future__ import annotations

from typing import Any, Iterator, Optional, TYPE_CHECKING
from urllib.parse import quote

from ._base import ListOptions
from .scheduled_session import ScheduledSession, ScheduledSessionList

if TYPE_CHECKING:
    from .client import AmbientClient


class ScheduledSessionAPI:
    def __init__(self, client: AmbientClient) -> None:
        self._client = client
    def _base_path(self) -> str:
        return "/projects/{id}/scheduled-sessions".replace("{id}", quote(self._client._project, safe=""))


    def create(self, data: dict) -> ScheduledSession:
        resp = self._client._request("POST", self._base_path(), json=data)
        return ScheduledSession.from_dict(resp)

    def get(self, resource_id: str) -> ScheduledSession:
        resp = self._client._request("GET", f"{self._base_path()}/{resource_id}")
        return ScheduledSession.from_dict(resp)

    def list(self, opts: Optional[ListOptions] = None) -> ScheduledSessionList:
        params = opts.to_params() if opts else None
        resp = self._client._request("GET", self._base_path(), params=params)
        return ScheduledSessionList.from_dict(resp)
    def update(self, resource_id: str, patch: Any) -> ScheduledSession:
        data = patch.to_dict() if hasattr(patch, "to_dict") else patch
        resp = self._client._request("PATCH", f"{self._base_path()}/{resource_id}", json=data)
        return ScheduledSession.from_dict(resp)

    def delete(self, resource_id: str) -> None:
        self._client._request("DELETE", f"{self._base_path()}/{resource_id}", expect_json=False)

    def resume(self, resource_id: str) -> ScheduledSession:
        resp = self._client._request("POST", f"{self._base_path()}/{resource_id}/resume")
        return ScheduledSession.from_dict(resp)

    def runs(self, resource_id: str) -> dict:
        resp = self._client._request("GET", f"{self._base_path()}/{resource_id}/runs")
        return resp

    def suspend(self, resource_id: str) -> ScheduledSession:
        resp = self._client._request("POST", f"{self._base_path()}/{resource_id}/suspend")
        return ScheduledSession.from_dict(resp)

    def trigger(self, resource_id: str) -> dict:
        resp = self._client._request("POST", f"{self._base_path()}/{resource_id}/trigger")
        return resp

    def list_all(self, size: int = 100, **kwargs: Any) -> Iterator[ScheduledSession]:
        page = 1
        while True:
            result = self.list(ListOptions().page(page).size(size))
            yield from result.items
            if page * size >= result.total:
                break
            page += 1
