# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: da9fbb26cd926e7df1af31ad78f47d005fd328228df521e9e3411636e5069455
# Generated: 2026-05-13T23:03:22Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Agent:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    annotations: str = ""
    bot_account_name: str = ""
    current_session_id: str = ""
    description: str = ""
    display_name: str = ""
    environment_variables: str = ""
    labels: str = ""
    llm_max_tokens: int = 0
    llm_model: str = ""
    llm_temperature: float = 0.0
    name: str = ""
    owner_user_id: str = ""
    parent_agent_id: str = ""
    project_id: str = ""
    prompt: str = ""
    repo_url: str = ""
    resource_overrides: str = ""
    workflow_id: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> Agent:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            annotations=data.get("annotations", ""),
            bot_account_name=data.get("bot_account_name", ""),
            current_session_id=data.get("current_session_id", ""),
            description=data.get("description", ""),
            display_name=data.get("display_name", ""),
            environment_variables=data.get("environment_variables", ""),
            labels=data.get("labels", ""),
            llm_max_tokens=data.get("llm_max_tokens", 0),
            llm_model=data.get("llm_model", ""),
            llm_temperature=data.get("llm_temperature", 0.0),
            name=data.get("name", ""),
            owner_user_id=data.get("owner_user_id", ""),
            parent_agent_id=data.get("parent_agent_id", ""),
            project_id=data.get("project_id", ""),
            prompt=data.get("prompt", ""),
            repo_url=data.get("repo_url", ""),
            resource_overrides=data.get("resource_overrides", ""),
            workflow_id=data.get("workflow_id", ""),
        )

    @classmethod
    def builder(cls) -> AgentBuilder:
        return AgentBuilder()


@dataclass(frozen=True)
class AgentList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[Agent] = ()

    @classmethod
    def from_dict(cls, data: dict) -> AgentList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Agent.from_dict(item) for item in data.get("items", [])],
        )


class AgentBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> AgentBuilder:
        self._data["annotations"] = value
        return self

    def bot_account_name(self, value: str) -> AgentBuilder:
        self._data["bot_account_name"] = value
        return self

    def description(self, value: str) -> AgentBuilder:
        self._data["description"] = value
        return self

    def display_name(self, value: str) -> AgentBuilder:
        self._data["display_name"] = value
        return self

    def environment_variables(self, value: str) -> AgentBuilder:
        self._data["environment_variables"] = value
        return self

    def labels(self, value: str) -> AgentBuilder:
        self._data["labels"] = value
        return self

    def llm_max_tokens(self, value: int) -> AgentBuilder:
        self._data["llm_max_tokens"] = value
        return self

    def llm_model(self, value: str) -> AgentBuilder:
        self._data["llm_model"] = value
        return self

    def llm_temperature(self, value: float) -> AgentBuilder:
        self._data["llm_temperature"] = value
        return self

    def name(self, value: str) -> AgentBuilder:
        self._data["name"] = value
        return self

    def owner_user_id(self, value: str) -> AgentBuilder:
        self._data["owner_user_id"] = value
        return self

    def parent_agent_id(self, value: str) -> AgentBuilder:
        self._data["parent_agent_id"] = value
        return self

    def project_id(self, value: str) -> AgentBuilder:
        self._data["project_id"] = value
        return self

    def prompt(self, value: str) -> AgentBuilder:
        self._data["prompt"] = value
        return self

    def repo_url(self, value: str) -> AgentBuilder:
        self._data["repo_url"] = value
        return self

    def resource_overrides(self, value: str) -> AgentBuilder:
        self._data["resource_overrides"] = value
        return self

    def workflow_id(self, value: str) -> AgentBuilder:
        self._data["workflow_id"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        if "project_id" not in self._data:
            raise ValueError("project_id is required")
        return dict(self._data)


class AgentPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> AgentPatch:
        self._data["annotations"] = value
        return self

    def description(self, value: str) -> AgentPatch:
        self._data["description"] = value
        return self

    def display_name(self, value: str) -> AgentPatch:
        self._data["display_name"] = value
        return self

    def labels(self, value: str) -> AgentPatch:
        self._data["labels"] = value
        return self

    def llm_max_tokens(self, value: int) -> AgentPatch:
        self._data["llm_max_tokens"] = value
        return self

    def llm_model(self, value: str) -> AgentPatch:
        self._data["llm_model"] = value
        return self

    def llm_temperature(self, value: float) -> AgentPatch:
        self._data["llm_temperature"] = value
        return self

    def name(self, value: str) -> AgentPatch:
        self._data["name"] = value
        return self

    def prompt(self, value: str) -> AgentPatch:
        self._data["prompt"] = value
        return self

    def repo_url(self, value: str) -> AgentPatch:
        self._data["repo_url"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
