# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: a45fc06b261cd394c9ceb9817484b3742fa24f7acf8e2adaeb15ea4ec80ec86b
# Generated: 2026-06-17T18:27:02Z

from __future__ import annotations

import json
import os
import re
from typing import Any, Optional, Union, TYPE_CHECKING
from urllib.parse import urlparse

import httpx

from ._base import APIError, ListOptions

if TYPE_CHECKING:
    from ._agent_api import AgentAPI
    from ._credential_api import CredentialAPI
    from ._inbox_message_api import InboxMessageAPI
    from ._project_api import ProjectAPI
    from ._project_settings_api import ProjectSettingsAPI
    from ._role_api import RoleAPI
    from ._role_binding_api import RoleBindingAPI
    from ._scheduled_session_api import ScheduledSessionAPI
    from ._session_api import SessionAPI
    from ._session_message_api import SessionMessageAPI
    from ._user_api import UserAPI


class AmbientClient:
    """HTTP client for the Ambient Platform API."""

    _base_path = "/api/ambient/v1"

    def __init__(
        self,
        base_url: str,
        token: str,
        project: str,
        *,
        timeout: float = 30.0,
        user_agent: str = "ambient-python-sdk/1.0.0",
    ) -> None:
        self._base_url = base_url.rstrip("/")
        self._token = token
        self._project = project
        self._timeout = timeout
        self._user_agent = user_agent

        self._validate_config()

        self._client = httpx.Client(
            timeout=timeout,
            headers={
                "User-Agent": user_agent,
                "Accept": "application/json",
            },
        )

        # Initialize API interfaces
        self._agent_api: Optional[AgentAPI] = None
        self._credential_api: Optional[CredentialAPI] = None
        self._inbox_message_api: Optional[InboxMessageAPI] = None
        self._project_api: Optional[ProjectAPI] = None
        self._project_settings_api: Optional[ProjectSettingsAPI] = None
        self._role_api: Optional[RoleAPI] = None
        self._role_binding_api: Optional[RoleBindingAPI] = None
        self._scheduled_session_api: Optional[ScheduledSessionAPI] = None
        self._session_api: Optional[SessionAPI] = None
        self._session_message_api: Optional[SessionMessageAPI] = None
        self._user_api: Optional[UserAPI] = None

    @classmethod
    def from_env(cls, **kwargs: Any) -> AmbientClient:
        """Create client from environment variables."""
        base_url = os.environ.get("AMBIENT_API_URL", "http://localhost:8080")
        token = os.environ.get("AMBIENT_TOKEN")
        project = os.environ.get("AMBIENT_PROJECT")

        if not token:
            raise ValueError("AMBIENT_TOKEN environment variable is required")
        if not project:
            raise ValueError("AMBIENT_PROJECT environment variable is required")

        return cls(base_url=base_url, token=token, project=project, **kwargs)

    def _validate_config(self) -> None:
        """Validate client configuration."""
        if not self._base_url:
            raise ValueError("base URL cannot be empty")

        parsed = urlparse(self._base_url)
        if parsed.scheme not in ("http", "https"):
            raise ValueError("URL scheme must be http or https")

        hostname = parsed.hostname or ""
        if hostname in ("example.com", "placeholder") or "placeholder" in hostname:
            raise ValueError("placeholder domain is not allowed")

        if not self._token:
            raise ValueError("token cannot be empty")

        if len(self._token) < 20:
            raise ValueError("token is too short (minimum 20 characters)")

        if self._token in ("YOUR_TOKEN_HERE", "PLACEHOLDER_TOKEN"):
            raise ValueError("placeholder token is not allowed")

        if not self._project:
            raise ValueError("project cannot be empty")

        if len(self._project) > 63:
            raise ValueError("project name cannot exceed 63 characters")

        if not re.match(r'^[a-z0-9_-]+$', self._project):
            raise ValueError("project name must contain only lowercase alphanumeric characters, hyphens, and underscores")

    def _request(
        self,
        method: str,
        path: str,
        *,
        json: Optional[dict[str, Any]] = None,
        params: Optional[dict[str, Any]] = None,
        expect_json: bool = True,
    ) -> Any:
        """Make HTTP request to the API."""
        url = self._base_url + "/api/ambient/v1" + path

        headers = {
            "Authorization": f"Bearer {self._token}",
            "X-Ambient-Project": self._project,
        }

        if json is not None:
            headers["Content-Type"] = "application/json"

        try:
            response = self._client.request(
                method=method,
                url=url,
                headers=headers,
                json=json,
                params=params,
            )

            self._handle_response(response, expect_json)

            if expect_json and response.content:
                return response.json()

            return None

        except httpx.RequestError as e:
            raise APIError(f"Request failed: {e}") from e

    def _handle_response(self, response: httpx.Response, expect_json: bool) -> None:
        """Handle HTTP response, raising appropriate errors."""
        if response.is_success:
            return

        try:
            if response.content and expect_json:
                error_data = response.json()
                if isinstance(error_data, dict) and "code" in error_data:
                    raise APIError.from_dict(error_data, response.status_code)
        except (json.JSONDecodeError, ValueError):
            pass

        # Fall back to generic error
        raise APIError.from_dict(
            {"reason": f"HTTP {response.status_code}: {response.reason_phrase}"},
            response.status_code
        )

    def close(self) -> None:
        """Close the underlying HTTP client."""
        self._client.close()

    def __enter__(self) -> AmbientClient:
        return self

    def __exit__(self, *args: Any) -> None:
        self.close()
    @property
    def agents(self) -> AgentAPI:
        """Get the Agent API interface."""
        if self._agent_api is None:
            from ._agent_api import AgentAPI
            self._agent_api = AgentAPI(self)
        return self._agent_api
    @property
    def credentials(self) -> CredentialAPI:
        """Get the Credential API interface."""
        if self._credential_api is None:
            from ._credential_api import CredentialAPI
            self._credential_api = CredentialAPI(self)
        return self._credential_api
    @property
    def inbox_messages(self) -> InboxMessageAPI:
        """Get the InboxMessage API interface."""
        if self._inbox_message_api is None:
            from ._inbox_message_api import InboxMessageAPI
            self._inbox_message_api = InboxMessageAPI(self)
        return self._inbox_message_api
    @property
    def projects(self) -> ProjectAPI:
        """Get the Project API interface."""
        if self._project_api is None:
            from ._project_api import ProjectAPI
            self._project_api = ProjectAPI(self)
        return self._project_api
    @property
    def project_settings(self) -> ProjectSettingsAPI:
        """Get the ProjectSettings API interface."""
        if self._project_settings_api is None:
            from ._project_settings_api import ProjectSettingsAPI
            self._project_settings_api = ProjectSettingsAPI(self)
        return self._project_settings_api
    @property
    def roles(self) -> RoleAPI:
        """Get the Role API interface."""
        if self._role_api is None:
            from ._role_api import RoleAPI
            self._role_api = RoleAPI(self)
        return self._role_api
    @property
    def role_bindings(self) -> RoleBindingAPI:
        """Get the RoleBinding API interface."""
        if self._role_binding_api is None:
            from ._role_binding_api import RoleBindingAPI
            self._role_binding_api = RoleBindingAPI(self)
        return self._role_binding_api
    @property
    def scheduled_sessions(self) -> ScheduledSessionAPI:
        """Get the ScheduledSession API interface."""
        if self._scheduled_session_api is None:
            from ._scheduled_session_api import ScheduledSessionAPI
            self._scheduled_session_api = ScheduledSessionAPI(self)
        return self._scheduled_session_api
    @property
    def sessions(self) -> SessionAPI:
        """Get the Session API interface."""
        if self._session_api is None:
            from ._session_api import SessionAPI
            self._session_api = SessionAPI(self)
        return self._session_api
    @property
    def session_messages(self) -> SessionMessageAPI:
        """Get the SessionMessage API interface."""
        if self._session_message_api is None:
            from ._session_message_api import SessionMessageAPI
            self._session_message_api = SessionMessageAPI(self)
        return self._session_message_api
    @property
    def users(self) -> UserAPI:
        """Get the User API interface."""
        if self._user_api is None:
            from ._user_api import UserAPI
            self._user_api = UserAPI(self)
        return self._user_api
