# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: c0552a0db4fdb51e6e5cf28c453ea87920416eaa69cdca8a78e6063c513b7bab
# Generated: 2026-07-20T04:51:09Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Cluster:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    annotations: str = ""
    api_server_url: str = ""
    capacity: str = ""
    credential_id: str = ""
    description: str = ""
    labels: str = ""
    last_heartbeat_at: Optional[datetime] = None
    name: str = ""
    role: str = ""
    status: str = ""
    status_message: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> Cluster:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            annotations=data.get("annotations", ""),
            api_server_url=data.get("api_server_url", ""),
            capacity=data.get("capacity", ""),
            credential_id=data.get("credential_id", ""),
            description=data.get("description", ""),
            labels=data.get("labels", ""),
            last_heartbeat_at=_parse_datetime(data.get("last_heartbeat_at")),
            name=data.get("name", ""),
            role=data.get("role", ""),
            status=data.get("status", ""),
            status_message=data.get("status_message", ""),
        )

    @classmethod
    def builder(cls) -> ClusterBuilder:
        return ClusterBuilder()


@dataclass(frozen=True)
class ClusterList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[Cluster] = ()

    @classmethod
    def from_dict(cls, data: dict) -> ClusterList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Cluster.from_dict(item) for item in data.get("items", [])],
        )


class ClusterBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> ClusterBuilder:
        self._data["annotations"] = value
        return self

    def api_server_url(self, value: str) -> ClusterBuilder:
        self._data["api_server_url"] = value
        return self

    def credential_id(self, value: str) -> ClusterBuilder:
        self._data["credential_id"] = value
        return self

    def description(self, value: str) -> ClusterBuilder:
        self._data["description"] = value
        return self

    def labels(self, value: str) -> ClusterBuilder:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> ClusterBuilder:
        self._data["name"] = value
        return self

    def role(self, value: str) -> ClusterBuilder:
        self._data["role"] = value
        return self

    def build(self) -> dict:
        if "api_server_url" not in self._data:
            raise ValueError("api_server_url is required")
        if "name" not in self._data:
            raise ValueError("name is required")
        if "role" not in self._data:
            raise ValueError("role is required")
        return dict(self._data)


class ClusterPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> ClusterPatch:
        self._data["annotations"] = value
        return self

    def api_server_url(self, value: str) -> ClusterPatch:
        self._data["api_server_url"] = value
        return self

    def credential_id(self, value: str) -> ClusterPatch:
        self._data["credential_id"] = value
        return self

    def description(self, value: str) -> ClusterPatch:
        self._data["description"] = value
        return self

    def labels(self, value: str) -> ClusterPatch:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> ClusterPatch:
        self._data["name"] = value
        return self

    def role(self, value: str) -> ClusterPatch:
        self._data["role"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)


@dataclass(frozen=True)
class ClusterStatusResponse:
    capacity: str = ""
    id: str = ""
    last_heartbeat_at: Optional[datetime] = None
    status: str = ""
    status_message: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> ClusterStatusResponse:
        return cls(
            capacity=data.get("capacity", ""),
            id=data.get("id", ""),
            last_heartbeat_at=_parse_datetime(data.get("last_heartbeat_at")),
            status=data.get("status", ""),
            status_message=data.get("status_message", ""),
        )
