# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: c0552a0db4fdb51e6e5cf28c453ea87920416eaa69cdca8a78e6063c513b7bab
# Generated: 2026-07-20T04:51:09Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Credential:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    annotations: str = ""
    description: str = ""
    email: str = ""
    labels: str = ""
    name: str = ""
    provider: str = ""
    token: str = ""
    url: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> Credential:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            annotations=data.get("annotations", ""),
            description=data.get("description", ""),
            email=data.get("email", ""),
            labels=data.get("labels", ""),
            name=data.get("name", ""),
            provider=data.get("provider", ""),
            token=data.get("token", ""),
            url=data.get("url", ""),
        )

    @classmethod
    def builder(cls) -> CredentialBuilder:
        return CredentialBuilder()


@dataclass(frozen=True)
class CredentialList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[Credential] = ()

    @classmethod
    def from_dict(cls, data: dict) -> CredentialList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Credential.from_dict(item) for item in data.get("items", [])],
        )


class CredentialBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> CredentialBuilder:
        self._data["annotations"] = value
        return self

    def description(self, value: str) -> CredentialBuilder:
        self._data["description"] = value
        return self

    def email(self, value: str) -> CredentialBuilder:
        self._data["email"] = value
        return self

    def labels(self, value: str) -> CredentialBuilder:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> CredentialBuilder:
        self._data["name"] = value
        return self

    def provider(self, value: str) -> CredentialBuilder:
        self._data["provider"] = value
        return self

    def token(self, value: str) -> CredentialBuilder:
        self._data["token"] = value
        return self

    def url(self, value: str) -> CredentialBuilder:
        self._data["url"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        if "provider" not in self._data:
            raise ValueError("provider is required")
        return dict(self._data)


class CredentialPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> CredentialPatch:
        self._data["annotations"] = value
        return self

    def description(self, value: str) -> CredentialPatch:
        self._data["description"] = value
        return self

    def email(self, value: str) -> CredentialPatch:
        self._data["email"] = value
        return self

    def labels(self, value: str) -> CredentialPatch:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> CredentialPatch:
        self._data["name"] = value
        return self

    def provider(self, value: str) -> CredentialPatch:
        self._data["provider"] = value
        return self

    def token(self, value: str) -> CredentialPatch:
        self._data["token"] = value
        return self

    def url(self, value: str) -> CredentialPatch:
        self._data["url"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
