# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 84c6a5120d178ae5bb13cd53f756c9ec09c9127f381cf380f9bfc8f8d5de4412
# Generated: 2026-07-15T03:32:32Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Gateway:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    annotations: str = ""
    config: str = ""
    image: str = ""
    labels: str = ""
    name: str = ""
    oidc: dict = ""
    project_id: str = ""
    server_dns_names: list[str] = ""

    @classmethod
    def from_dict(cls, data: dict) -> Gateway:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            annotations=data.get("annotations", ""),
            config=data.get("config", ""),
            image=data.get("image", ""),
            labels=data.get("labels", ""),
            name=data.get("name", ""),
            oidc=data.get("oidc", ""),
            project_id=data.get("project_id", ""),
            server_dns_names=data.get("server_dns_names", ""),
        )

    @classmethod
    def builder(cls) -> GatewayBuilder:
        return GatewayBuilder()


@dataclass(frozen=True)
class GatewayList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[Gateway] = ()

    @classmethod
    def from_dict(cls, data: dict) -> GatewayList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Gateway.from_dict(item) for item in data.get("items", [])],
        )


class GatewayBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> GatewayBuilder:
        self._data["annotations"] = value
        return self

    def config(self, value: str) -> GatewayBuilder:
        self._data["config"] = value
        return self

    def image(self, value: str) -> GatewayBuilder:
        self._data["image"] = value
        return self

    def labels(self, value: str) -> GatewayBuilder:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> GatewayBuilder:
        self._data["name"] = value
        return self

    def oidc(self, value: dict) -> GatewayBuilder:
        self._data["oidc"] = value
        return self

    def project_id(self, value: str) -> GatewayBuilder:
        self._data["project_id"] = value
        return self

    def server_dns_names(self, value: list[str]) -> GatewayBuilder:
        self._data["server_dns_names"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        if "project_id" not in self._data:
            raise ValueError("project_id is required")
        return dict(self._data)


class GatewayPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> GatewayPatch:
        self._data["annotations"] = value
        return self

    def config(self, value: str) -> GatewayPatch:
        self._data["config"] = value
        return self

    def image(self, value: str) -> GatewayPatch:
        self._data["image"] = value
        return self

    def labels(self, value: str) -> GatewayPatch:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> GatewayPatch:
        self._data["name"] = value
        return self

    def oidc(self, value: dict) -> GatewayPatch:
        self._data["oidc"] = value
        return self

    def server_dns_names(self, value: list[str]) -> GatewayPatch:
        self._data["server_dns_names"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
