# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: c9d4494778eb0a006db1f289630460fb9b5dc58df1895903c42735b4f56b0314
# Generated: 2026-05-05T18:24:54Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Project:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    annotations: str = ""
    description: str = ""
    display_name: str = ""
    labels: str = ""
    name: str = ""
    prompt: str = ""
    status: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> Project:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            annotations=data.get("annotations", ""),
            description=data.get("description", ""),
            display_name=data.get("display_name", ""),
            labels=data.get("labels", ""),
            name=data.get("name", ""),
            prompt=data.get("prompt", ""),
            status=data.get("status", ""),
        )

    @classmethod
    def builder(cls) -> ProjectBuilder:
        return ProjectBuilder()


@dataclass(frozen=True)
class ProjectList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[Project] = ()

    @classmethod
    def from_dict(cls, data: dict) -> ProjectList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Project.from_dict(item) for item in data.get("items", [])],
        )


class ProjectBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> ProjectBuilder:
        self._data["annotations"] = value
        return self

    def description(self, value: str) -> ProjectBuilder:
        self._data["description"] = value
        return self

    def display_name(self, value: str) -> ProjectBuilder:
        self._data["display_name"] = value
        return self

    def labels(self, value: str) -> ProjectBuilder:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> ProjectBuilder:
        self._data["name"] = value
        return self

    def prompt(self, value: str) -> ProjectBuilder:
        self._data["prompt"] = value
        return self

    def status(self, value: str) -> ProjectBuilder:
        self._data["status"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        return dict(self._data)


class ProjectPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> ProjectPatch:
        self._data["annotations"] = value
        return self

    def description(self, value: str) -> ProjectPatch:
        self._data["description"] = value
        return self

    def display_name(self, value: str) -> ProjectPatch:
        self._data["display_name"] = value
        return self

    def labels(self, value: str) -> ProjectPatch:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> ProjectPatch:
        self._data["name"] = value
        return self

    def prompt(self, value: str) -> ProjectPatch:
        self._data["prompt"] = value
        return self

    def status(self, value: str) -> ProjectPatch:
        self._data["status"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
