# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: ed0a896aa0e4678be21149b07fe658b66ddc41e3d4b41b372e8cf6377e8c927e
# Generated: 2026-06-30T15:47:18Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class ProjectSettings:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    group_access: str = ""
    project_id: str = ""
    repositories: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> ProjectSettings:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            group_access=data.get("group_access", ""),
            project_id=data.get("project_id", ""),
            repositories=data.get("repositories", ""),
        )

    @classmethod
    def builder(cls) -> ProjectSettingsBuilder:
        return ProjectSettingsBuilder()


@dataclass(frozen=True)
class ProjectSettingsList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[ProjectSettings] = ()

    @classmethod
    def from_dict(cls, data: dict) -> ProjectSettingsList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[ProjectSettings.from_dict(item) for item in data.get("items", [])],
        )


class ProjectSettingsBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def group_access(self, value: str) -> ProjectSettingsBuilder:
        self._data["group_access"] = value
        return self

    def project_id(self, value: str) -> ProjectSettingsBuilder:
        self._data["project_id"] = value
        return self

    def repositories(self, value: str) -> ProjectSettingsBuilder:
        self._data["repositories"] = value
        return self

    def build(self) -> dict:
        if "project_id" not in self._data:
            raise ValueError("project_id is required")
        return dict(self._data)


class ProjectSettingsPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def group_access(self, value: str) -> ProjectSettingsPatch:
        self._data["group_access"] = value
        return self

    def project_id(self, value: str) -> ProjectSettingsPatch:
        self._data["project_id"] = value
        return self

    def repositories(self, value: str) -> ProjectSettingsPatch:
        self._data["repositories"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
