# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: c0552a0db4fdb51e6e5cf28c453ea87920416eaa69cdca8a78e6063c513b7bab
# Generated: 2026-07-20T04:51:09Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Provider:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    annotations: str = ""
    labels: str = ""
    name: str = ""
    namespace: str = ""
    project_id: str = ""
    secret: str = ""
    type: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> Provider:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            annotations=data.get("annotations", ""),
            labels=data.get("labels", ""),
            name=data.get("name", ""),
            namespace=data.get("namespace", ""),
            project_id=data.get("project_id", ""),
            secret=data.get("secret", ""),
            type=data.get("type", ""),
        )

    @classmethod
    def builder(cls) -> ProviderBuilder:
        return ProviderBuilder()


@dataclass(frozen=True)
class ProviderList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[Provider] = ()

    @classmethod
    def from_dict(cls, data: dict) -> ProviderList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Provider.from_dict(item) for item in data.get("items", [])],
        )


class ProviderBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> ProviderBuilder:
        self._data["annotations"] = value
        return self

    def labels(self, value: str) -> ProviderBuilder:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> ProviderBuilder:
        self._data["name"] = value
        return self

    def namespace(self, value: str) -> ProviderBuilder:
        self._data["namespace"] = value
        return self

    def project_id(self, value: str) -> ProviderBuilder:
        self._data["project_id"] = value
        return self

    def secret(self, value: str) -> ProviderBuilder:
        self._data["secret"] = value
        return self

    def type(self, value: str) -> ProviderBuilder:
        self._data["type"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        if "project_id" not in self._data:
            raise ValueError("project_id is required")
        return dict(self._data)


class ProviderPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def annotations(self, value: str) -> ProviderPatch:
        self._data["annotations"] = value
        return self

    def labels(self, value: str) -> ProviderPatch:
        self._data["labels"] = value
        return self

    def name(self, value: str) -> ProviderPatch:
        self._data["name"] = value
        return self

    def namespace(self, value: str) -> ProviderPatch:
        self._data["namespace"] = value
        return self

    def secret(self, value: str) -> ProviderPatch:
        self._data["secret"] = value
        return self

    def type(self, value: str) -> ProviderPatch:
        self._data["type"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
