# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 0d99d538cf2137af9c98c3b852de4b2c46377626d7f163abfb3af9423cad7afa
# Generated: 2026-07-08T01:48:22Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class Role:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    built_in: bool = False
    description: str = ""
    display_name: str = ""
    name: str = ""
    permissions: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> Role:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            built_in=data.get("built_in", False),
            description=data.get("description", ""),
            display_name=data.get("display_name", ""),
            name=data.get("name", ""),
            permissions=data.get("permissions", ""),
        )

    @classmethod
    def builder(cls) -> RoleBuilder:
        return RoleBuilder()


@dataclass(frozen=True)
class RoleList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[Role] = ()

    @classmethod
    def from_dict(cls, data: dict) -> RoleList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[Role.from_dict(item) for item in data.get("items", [])],
        )


class RoleBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def built_in(self, value: bool) -> RoleBuilder:
        self._data["built_in"] = value
        return self

    def description(self, value: str) -> RoleBuilder:
        self._data["description"] = value
        return self

    def display_name(self, value: str) -> RoleBuilder:
        self._data["display_name"] = value
        return self

    def name(self, value: str) -> RoleBuilder:
        self._data["name"] = value
        return self

    def permissions(self, value: str) -> RoleBuilder:
        self._data["permissions"] = value
        return self

    def build(self) -> dict:
        if "name" not in self._data:
            raise ValueError("name is required")
        return dict(self._data)


class RolePatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def built_in(self, value: bool) -> RolePatch:
        self._data["built_in"] = value
        return self

    def description(self, value: str) -> RolePatch:
        self._data["description"] = value
        return self

    def display_name(self, value: str) -> RolePatch:
        self._data["display_name"] = value
        return self

    def name(self, value: str) -> RolePatch:
        self._data["name"] = value
        return self

    def permissions(self, value: str) -> RolePatch:
        self._data["permissions"] = value
        return self

    def to_dict(self) -> dict:
        return dict(self._data)
