# Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
# Source: ../../ambient-api-server/openapi/openapi.yaml
# Spec SHA256: 84c6a5120d178ae5bb13cd53f756c9ec09c9127f381cf380f9bfc8f8d5de4412
# Generated: 2026-07-15T03:32:32Z

from __future__ import annotations

from dataclasses import dataclass
from datetime import datetime
from typing import Any, Optional

from ._base import ListMeta, _parse_datetime


@dataclass(frozen=True)
class SessionEvent:
    id: str = ""
    kind: str = ""
    href: str = ""
    created_at: Optional[datetime] = None
    updated_at: Optional[datetime] = None
    completed_at: Optional[datetime] = None
    event_count: int = 0
    event_type: str = ""
    payload: str = ""
    seq: int = 0
    session_id: str = ""

    @classmethod
    def from_dict(cls, data: dict) -> SessionEvent:
        return cls(
            id=data.get("id", ""),
            kind=data.get("kind", ""),
            href=data.get("href", ""),
            created_at=_parse_datetime(data.get("created_at")),
            updated_at=_parse_datetime(data.get("updated_at")),
            completed_at=_parse_datetime(data.get("completed_at")),
            event_count=data.get("event_count", 0),
            event_type=data.get("event_type", ""),
            payload=data.get("payload", ""),
            seq=data.get("seq", 0),
            session_id=data.get("session_id", ""),
        )

    @classmethod
    def builder(cls) -> SessionEventBuilder:
        return SessionEventBuilder()


@dataclass(frozen=True)
class SessionEventList:
    kind: str = ""
    page: int = 0
    size: int = 0
    total: int = 0
    items: list[SessionEvent] = ()

    @classmethod
    def from_dict(cls, data: dict) -> SessionEventList:
        return cls(
            kind=data.get("kind", ""),
            page=data.get("page", 0),
            size=data.get("size", 0),
            total=data.get("total", 0),
            items=[SessionEvent.from_dict(item) for item in data.get("items", [])],
        )


class SessionEventBuilder:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def event_type(self, value: str) -> SessionEventBuilder:
        self._data["event_type"] = value
        return self

    def payload(self, value: str) -> SessionEventBuilder:
        self._data["payload"] = value
        return self

    def build(self) -> dict:
        return dict(self._data)


class SessionEventPatch:
    def __init__(self) -> None:
        self._data: dict[str, Any] = {}


    def to_dict(self) -> dict:
        return dict(self._data)
