// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: ambient/v1/sessions.proto

package ambient_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Session struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Metadata             *ObjectReference       `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	Name                 string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	RepoUrl              *string                `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3,oneof" json:"repo_url,omitempty"`
	Prompt               *string                `protobuf:"bytes,4,opt,name=prompt,proto3,oneof" json:"prompt,omitempty"`
	CreatedByUserId      *string                `protobuf:"bytes,5,opt,name=created_by_user_id,json=createdByUserId,proto3,oneof" json:"created_by_user_id,omitempty"`
	AssignedUserId       *string                `protobuf:"bytes,6,opt,name=assigned_user_id,json=assignedUserId,proto3,oneof" json:"assigned_user_id,omitempty"`
	WorkflowId           *string                `protobuf:"bytes,7,opt,name=workflow_id,json=workflowId,proto3,oneof" json:"workflow_id,omitempty"`
	Repos                *string                `protobuf:"bytes,8,opt,name=repos,proto3,oneof" json:"repos,omitempty"`
	Timeout              *int32                 `protobuf:"varint,10,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	LlmModel             *string                `protobuf:"bytes,11,opt,name=llm_model,json=llmModel,proto3,oneof" json:"llm_model,omitempty"`
	LlmTemperature       *float64               `protobuf:"fixed64,12,opt,name=llm_temperature,json=llmTemperature,proto3,oneof" json:"llm_temperature,omitempty"`
	LlmMaxTokens         *int32                 `protobuf:"varint,13,opt,name=llm_max_tokens,json=llmMaxTokens,proto3,oneof" json:"llm_max_tokens,omitempty"`
	ParentSessionId      *string                `protobuf:"bytes,14,opt,name=parent_session_id,json=parentSessionId,proto3,oneof" json:"parent_session_id,omitempty"`
	BotAccountName       *string                `protobuf:"bytes,15,opt,name=bot_account_name,json=botAccountName,proto3,oneof" json:"bot_account_name,omitempty"`
	ResourceOverrides    *string                `protobuf:"bytes,16,opt,name=resource_overrides,json=resourceOverrides,proto3,oneof" json:"resource_overrides,omitempty"`
	EnvironmentVariables *string                `protobuf:"bytes,17,opt,name=environment_variables,json=environmentVariables,proto3,oneof" json:"environment_variables,omitempty"`
	Labels               *string                `protobuf:"bytes,18,opt,name=labels,proto3,oneof" json:"labels,omitempty"`
	Annotations          *string                `protobuf:"bytes,19,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	ProjectId            *string                `protobuf:"bytes,20,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	Phase                *string                `protobuf:"bytes,21,opt,name=phase,proto3,oneof" json:"phase,omitempty"`
	StartTime            *timestamppb.Timestamp `protobuf:"bytes,22,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	CompletionTime       *timestamppb.Timestamp `protobuf:"bytes,23,opt,name=completion_time,json=completionTime,proto3,oneof" json:"completion_time,omitempty"`
	SdkSessionId         *string                `protobuf:"bytes,24,opt,name=sdk_session_id,json=sdkSessionId,proto3,oneof" json:"sdk_session_id,omitempty"`
	SdkRestartCount      *int32                 `protobuf:"varint,25,opt,name=sdk_restart_count,json=sdkRestartCount,proto3,oneof" json:"sdk_restart_count,omitempty"`
	Conditions           *string                `protobuf:"bytes,26,opt,name=conditions,proto3,oneof" json:"conditions,omitempty"`
	ReconciledRepos      *string                `protobuf:"bytes,27,opt,name=reconciled_repos,json=reconciledRepos,proto3,oneof" json:"reconciled_repos,omitempty"`
	ReconciledWorkflow   *string                `protobuf:"bytes,28,opt,name=reconciled_workflow,json=reconciledWorkflow,proto3,oneof" json:"reconciled_workflow,omitempty"`
	KubeCrName           *string                `protobuf:"bytes,29,opt,name=kube_cr_name,json=kubeCrName,proto3,oneof" json:"kube_cr_name,omitempty"`
	KubeCrUid            *string                `protobuf:"bytes,30,opt,name=kube_cr_uid,json=kubeCrUid,proto3,oneof" json:"kube_cr_uid,omitempty"`
	KubeNamespace        *string                `protobuf:"bytes,31,opt,name=kube_namespace,json=kubeNamespace,proto3,oneof" json:"kube_namespace,omitempty"`
	AgentId              *string                `protobuf:"bytes,32,opt,name=agent_id,json=agentId,proto3,oneof" json:"agent_id,omitempty"`
	LastActivityAt       *timestamppb.Timestamp `protobuf:"bytes,33,opt,name=last_activity_at,json=lastActivityAt,proto3,oneof" json:"last_activity_at,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Session) Reset() {
	*x = Session{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Session) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Session) ProtoMessage() {}

func (x *Session) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Session.ProtoReflect.Descriptor instead.
func (*Session) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{0}
}

func (x *Session) GetMetadata() *ObjectReference {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Session) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Session) GetRepoUrl() string {
	if x != nil && x.RepoUrl != nil {
		return *x.RepoUrl
	}
	return ""
}

func (x *Session) GetPrompt() string {
	if x != nil && x.Prompt != nil {
		return *x.Prompt
	}
	return ""
}

func (x *Session) GetCreatedByUserId() string {
	if x != nil && x.CreatedByUserId != nil {
		return *x.CreatedByUserId
	}
	return ""
}

func (x *Session) GetAssignedUserId() string {
	if x != nil && x.AssignedUserId != nil {
		return *x.AssignedUserId
	}
	return ""
}

func (x *Session) GetWorkflowId() string {
	if x != nil && x.WorkflowId != nil {
		return *x.WorkflowId
	}
	return ""
}

func (x *Session) GetRepos() string {
	if x != nil && x.Repos != nil {
		return *x.Repos
	}
	return ""
}

func (x *Session) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *Session) GetLlmModel() string {
	if x != nil && x.LlmModel != nil {
		return *x.LlmModel
	}
	return ""
}

func (x *Session) GetLlmTemperature() float64 {
	if x != nil && x.LlmTemperature != nil {
		return *x.LlmTemperature
	}
	return 0
}

func (x *Session) GetLlmMaxTokens() int32 {
	if x != nil && x.LlmMaxTokens != nil {
		return *x.LlmMaxTokens
	}
	return 0
}

func (x *Session) GetParentSessionId() string {
	if x != nil && x.ParentSessionId != nil {
		return *x.ParentSessionId
	}
	return ""
}

func (x *Session) GetBotAccountName() string {
	if x != nil && x.BotAccountName != nil {
		return *x.BotAccountName
	}
	return ""
}

func (x *Session) GetResourceOverrides() string {
	if x != nil && x.ResourceOverrides != nil {
		return *x.ResourceOverrides
	}
	return ""
}

func (x *Session) GetEnvironmentVariables() string {
	if x != nil && x.EnvironmentVariables != nil {
		return *x.EnvironmentVariables
	}
	return ""
}

func (x *Session) GetLabels() string {
	if x != nil && x.Labels != nil {
		return *x.Labels
	}
	return ""
}

func (x *Session) GetAnnotations() string {
	if x != nil && x.Annotations != nil {
		return *x.Annotations
	}
	return ""
}

func (x *Session) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

func (x *Session) GetPhase() string {
	if x != nil && x.Phase != nil {
		return *x.Phase
	}
	return ""
}

func (x *Session) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *Session) GetCompletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionTime
	}
	return nil
}

func (x *Session) GetSdkSessionId() string {
	if x != nil && x.SdkSessionId != nil {
		return *x.SdkSessionId
	}
	return ""
}

func (x *Session) GetSdkRestartCount() int32 {
	if x != nil && x.SdkRestartCount != nil {
		return *x.SdkRestartCount
	}
	return 0
}

func (x *Session) GetConditions() string {
	if x != nil && x.Conditions != nil {
		return *x.Conditions
	}
	return ""
}

func (x *Session) GetReconciledRepos() string {
	if x != nil && x.ReconciledRepos != nil {
		return *x.ReconciledRepos
	}
	return ""
}

func (x *Session) GetReconciledWorkflow() string {
	if x != nil && x.ReconciledWorkflow != nil {
		return *x.ReconciledWorkflow
	}
	return ""
}

func (x *Session) GetKubeCrName() string {
	if x != nil && x.KubeCrName != nil {
		return *x.KubeCrName
	}
	return ""
}

func (x *Session) GetKubeCrUid() string {
	if x != nil && x.KubeCrUid != nil {
		return *x.KubeCrUid
	}
	return ""
}

func (x *Session) GetKubeNamespace() string {
	if x != nil && x.KubeNamespace != nil {
		return *x.KubeNamespace
	}
	return ""
}

func (x *Session) GetAgentId() string {
	if x != nil && x.AgentId != nil {
		return *x.AgentId
	}
	return ""
}

func (x *Session) GetLastActivityAt() *timestamppb.Timestamp {
	if x != nil {
		return x.LastActivityAt
	}
	return nil
}

type CreateSessionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Name                 string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	RepoUrl              *string                `protobuf:"bytes,2,opt,name=repo_url,json=repoUrl,proto3,oneof" json:"repo_url,omitempty"`
	Prompt               *string                `protobuf:"bytes,3,opt,name=prompt,proto3,oneof" json:"prompt,omitempty"`
	CreatedByUserId      *string                `protobuf:"bytes,4,opt,name=created_by_user_id,json=createdByUserId,proto3,oneof" json:"created_by_user_id,omitempty"`
	AssignedUserId       *string                `protobuf:"bytes,5,opt,name=assigned_user_id,json=assignedUserId,proto3,oneof" json:"assigned_user_id,omitempty"`
	WorkflowId           *string                `protobuf:"bytes,6,opt,name=workflow_id,json=workflowId,proto3,oneof" json:"workflow_id,omitempty"`
	Repos                *string                `protobuf:"bytes,7,opt,name=repos,proto3,oneof" json:"repos,omitempty"`
	Timeout              *int32                 `protobuf:"varint,9,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	LlmModel             *string                `protobuf:"bytes,10,opt,name=llm_model,json=llmModel,proto3,oneof" json:"llm_model,omitempty"`
	LlmTemperature       *float64               `protobuf:"fixed64,11,opt,name=llm_temperature,json=llmTemperature,proto3,oneof" json:"llm_temperature,omitempty"`
	LlmMaxTokens         *int32                 `protobuf:"varint,12,opt,name=llm_max_tokens,json=llmMaxTokens,proto3,oneof" json:"llm_max_tokens,omitempty"`
	ParentSessionId      *string                `protobuf:"bytes,13,opt,name=parent_session_id,json=parentSessionId,proto3,oneof" json:"parent_session_id,omitempty"`
	BotAccountName       *string                `protobuf:"bytes,14,opt,name=bot_account_name,json=botAccountName,proto3,oneof" json:"bot_account_name,omitempty"`
	ResourceOverrides    *string                `protobuf:"bytes,15,opt,name=resource_overrides,json=resourceOverrides,proto3,oneof" json:"resource_overrides,omitempty"`
	EnvironmentVariables *string                `protobuf:"bytes,16,opt,name=environment_variables,json=environmentVariables,proto3,oneof" json:"environment_variables,omitempty"`
	Labels               *string                `protobuf:"bytes,17,opt,name=labels,proto3,oneof" json:"labels,omitempty"`
	Annotations          *string                `protobuf:"bytes,18,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	ProjectId            *string                `protobuf:"bytes,19,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateSessionRequest) GetRepoUrl() string {
	if x != nil && x.RepoUrl != nil {
		return *x.RepoUrl
	}
	return ""
}

func (x *CreateSessionRequest) GetPrompt() string {
	if x != nil && x.Prompt != nil {
		return *x.Prompt
	}
	return ""
}

func (x *CreateSessionRequest) GetCreatedByUserId() string {
	if x != nil && x.CreatedByUserId != nil {
		return *x.CreatedByUserId
	}
	return ""
}

func (x *CreateSessionRequest) GetAssignedUserId() string {
	if x != nil && x.AssignedUserId != nil {
		return *x.AssignedUserId
	}
	return ""
}

func (x *CreateSessionRequest) GetWorkflowId() string {
	if x != nil && x.WorkflowId != nil {
		return *x.WorkflowId
	}
	return ""
}

func (x *CreateSessionRequest) GetRepos() string {
	if x != nil && x.Repos != nil {
		return *x.Repos
	}
	return ""
}

func (x *CreateSessionRequest) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *CreateSessionRequest) GetLlmModel() string {
	if x != nil && x.LlmModel != nil {
		return *x.LlmModel
	}
	return ""
}

func (x *CreateSessionRequest) GetLlmTemperature() float64 {
	if x != nil && x.LlmTemperature != nil {
		return *x.LlmTemperature
	}
	return 0
}

func (x *CreateSessionRequest) GetLlmMaxTokens() int32 {
	if x != nil && x.LlmMaxTokens != nil {
		return *x.LlmMaxTokens
	}
	return 0
}

func (x *CreateSessionRequest) GetParentSessionId() string {
	if x != nil && x.ParentSessionId != nil {
		return *x.ParentSessionId
	}
	return ""
}

func (x *CreateSessionRequest) GetBotAccountName() string {
	if x != nil && x.BotAccountName != nil {
		return *x.BotAccountName
	}
	return ""
}

func (x *CreateSessionRequest) GetResourceOverrides() string {
	if x != nil && x.ResourceOverrides != nil {
		return *x.ResourceOverrides
	}
	return ""
}

func (x *CreateSessionRequest) GetEnvironmentVariables() string {
	if x != nil && x.EnvironmentVariables != nil {
		return *x.EnvironmentVariables
	}
	return ""
}

func (x *CreateSessionRequest) GetLabels() string {
	if x != nil && x.Labels != nil {
		return *x.Labels
	}
	return ""
}

func (x *CreateSessionRequest) GetAnnotations() string {
	if x != nil && x.Annotations != nil {
		return *x.Annotations
	}
	return ""
}

func (x *CreateSessionRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

type GetSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSessionRequest) Reset() {
	*x = GetSessionRequest{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSessionRequest) ProtoMessage() {}

func (x *GetSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSessionRequest.ProtoReflect.Descriptor instead.
func (*GetSessionRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{2}
}

func (x *GetSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type UpdateSessionRequest struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	Id                   string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	RepoUrl              *string                `protobuf:"bytes,3,opt,name=repo_url,json=repoUrl,proto3,oneof" json:"repo_url,omitempty"`
	Prompt               *string                `protobuf:"bytes,4,opt,name=prompt,proto3,oneof" json:"prompt,omitempty"`
	AssignedUserId       *string                `protobuf:"bytes,5,opt,name=assigned_user_id,json=assignedUserId,proto3,oneof" json:"assigned_user_id,omitempty"`
	WorkflowId           *string                `protobuf:"bytes,6,opt,name=workflow_id,json=workflowId,proto3,oneof" json:"workflow_id,omitempty"`
	Repos                *string                `protobuf:"bytes,7,opt,name=repos,proto3,oneof" json:"repos,omitempty"`
	Timeout              *int32                 `protobuf:"varint,9,opt,name=timeout,proto3,oneof" json:"timeout,omitempty"`
	LlmModel             *string                `protobuf:"bytes,10,opt,name=llm_model,json=llmModel,proto3,oneof" json:"llm_model,omitempty"`
	LlmTemperature       *float64               `protobuf:"fixed64,11,opt,name=llm_temperature,json=llmTemperature,proto3,oneof" json:"llm_temperature,omitempty"`
	LlmMaxTokens         *int32                 `protobuf:"varint,12,opt,name=llm_max_tokens,json=llmMaxTokens,proto3,oneof" json:"llm_max_tokens,omitempty"`
	ParentSessionId      *string                `protobuf:"bytes,13,opt,name=parent_session_id,json=parentSessionId,proto3,oneof" json:"parent_session_id,omitempty"`
	BotAccountName       *string                `protobuf:"bytes,14,opt,name=bot_account_name,json=botAccountName,proto3,oneof" json:"bot_account_name,omitempty"`
	ResourceOverrides    *string                `protobuf:"bytes,15,opt,name=resource_overrides,json=resourceOverrides,proto3,oneof" json:"resource_overrides,omitempty"`
	EnvironmentVariables *string                `protobuf:"bytes,16,opt,name=environment_variables,json=environmentVariables,proto3,oneof" json:"environment_variables,omitempty"`
	Labels               *string                `protobuf:"bytes,17,opt,name=labels,proto3,oneof" json:"labels,omitempty"`
	Annotations          *string                `protobuf:"bytes,18,opt,name=annotations,proto3,oneof" json:"annotations,omitempty"`
	ProjectId            *string                `protobuf:"bytes,19,opt,name=project_id,json=projectId,proto3,oneof" json:"project_id,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *UpdateSessionRequest) Reset() {
	*x = UpdateSessionRequest{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionRequest) ProtoMessage() {}

func (x *UpdateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSessionRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateSessionRequest) GetRepoUrl() string {
	if x != nil && x.RepoUrl != nil {
		return *x.RepoUrl
	}
	return ""
}

func (x *UpdateSessionRequest) GetPrompt() string {
	if x != nil && x.Prompt != nil {
		return *x.Prompt
	}
	return ""
}

func (x *UpdateSessionRequest) GetAssignedUserId() string {
	if x != nil && x.AssignedUserId != nil {
		return *x.AssignedUserId
	}
	return ""
}

func (x *UpdateSessionRequest) GetWorkflowId() string {
	if x != nil && x.WorkflowId != nil {
		return *x.WorkflowId
	}
	return ""
}

func (x *UpdateSessionRequest) GetRepos() string {
	if x != nil && x.Repos != nil {
		return *x.Repos
	}
	return ""
}

func (x *UpdateSessionRequest) GetTimeout() int32 {
	if x != nil && x.Timeout != nil {
		return *x.Timeout
	}
	return 0
}

func (x *UpdateSessionRequest) GetLlmModel() string {
	if x != nil && x.LlmModel != nil {
		return *x.LlmModel
	}
	return ""
}

func (x *UpdateSessionRequest) GetLlmTemperature() float64 {
	if x != nil && x.LlmTemperature != nil {
		return *x.LlmTemperature
	}
	return 0
}

func (x *UpdateSessionRequest) GetLlmMaxTokens() int32 {
	if x != nil && x.LlmMaxTokens != nil {
		return *x.LlmMaxTokens
	}
	return 0
}

func (x *UpdateSessionRequest) GetParentSessionId() string {
	if x != nil && x.ParentSessionId != nil {
		return *x.ParentSessionId
	}
	return ""
}

func (x *UpdateSessionRequest) GetBotAccountName() string {
	if x != nil && x.BotAccountName != nil {
		return *x.BotAccountName
	}
	return ""
}

func (x *UpdateSessionRequest) GetResourceOverrides() string {
	if x != nil && x.ResourceOverrides != nil {
		return *x.ResourceOverrides
	}
	return ""
}

func (x *UpdateSessionRequest) GetEnvironmentVariables() string {
	if x != nil && x.EnvironmentVariables != nil {
		return *x.EnvironmentVariables
	}
	return ""
}

func (x *UpdateSessionRequest) GetLabels() string {
	if x != nil && x.Labels != nil {
		return *x.Labels
	}
	return ""
}

func (x *UpdateSessionRequest) GetAnnotations() string {
	if x != nil && x.Annotations != nil {
		return *x.Annotations
	}
	return ""
}

func (x *UpdateSessionRequest) GetProjectId() string {
	if x != nil && x.ProjectId != nil {
		return *x.ProjectId
	}
	return ""
}

type UpdateSessionStatusRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Phase              *string                `protobuf:"bytes,2,opt,name=phase,proto3,oneof" json:"phase,omitempty"`
	StartTime          *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=start_time,json=startTime,proto3,oneof" json:"start_time,omitempty"`
	CompletionTime     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=completion_time,json=completionTime,proto3,oneof" json:"completion_time,omitempty"`
	SdkSessionId       *string                `protobuf:"bytes,5,opt,name=sdk_session_id,json=sdkSessionId,proto3,oneof" json:"sdk_session_id,omitempty"`
	SdkRestartCount    *int32                 `protobuf:"varint,6,opt,name=sdk_restart_count,json=sdkRestartCount,proto3,oneof" json:"sdk_restart_count,omitempty"`
	Conditions         *string                `protobuf:"bytes,7,opt,name=conditions,proto3,oneof" json:"conditions,omitempty"`
	ReconciledRepos    *string                `protobuf:"bytes,8,opt,name=reconciled_repos,json=reconciledRepos,proto3,oneof" json:"reconciled_repos,omitempty"`
	ReconciledWorkflow *string                `protobuf:"bytes,9,opt,name=reconciled_workflow,json=reconciledWorkflow,proto3,oneof" json:"reconciled_workflow,omitempty"`
	KubeCrUid          *string                `protobuf:"bytes,10,opt,name=kube_cr_uid,json=kubeCrUid,proto3,oneof" json:"kube_cr_uid,omitempty"`
	KubeNamespace      *string                `protobuf:"bytes,11,opt,name=kube_namespace,json=kubeNamespace,proto3,oneof" json:"kube_namespace,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *UpdateSessionStatusRequest) Reset() {
	*x = UpdateSessionStatusRequest{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateSessionStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateSessionStatusRequest) ProtoMessage() {}

func (x *UpdateSessionStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateSessionStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateSessionStatusRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{4}
}

func (x *UpdateSessionStatusRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *UpdateSessionStatusRequest) GetPhase() string {
	if x != nil && x.Phase != nil {
		return *x.Phase
	}
	return ""
}

func (x *UpdateSessionStatusRequest) GetStartTime() *timestamppb.Timestamp {
	if x != nil {
		return x.StartTime
	}
	return nil
}

func (x *UpdateSessionStatusRequest) GetCompletionTime() *timestamppb.Timestamp {
	if x != nil {
		return x.CompletionTime
	}
	return nil
}

func (x *UpdateSessionStatusRequest) GetSdkSessionId() string {
	if x != nil && x.SdkSessionId != nil {
		return *x.SdkSessionId
	}
	return ""
}

func (x *UpdateSessionStatusRequest) GetSdkRestartCount() int32 {
	if x != nil && x.SdkRestartCount != nil {
		return *x.SdkRestartCount
	}
	return 0
}

func (x *UpdateSessionStatusRequest) GetConditions() string {
	if x != nil && x.Conditions != nil {
		return *x.Conditions
	}
	return ""
}

func (x *UpdateSessionStatusRequest) GetReconciledRepos() string {
	if x != nil && x.ReconciledRepos != nil {
		return *x.ReconciledRepos
	}
	return ""
}

func (x *UpdateSessionStatusRequest) GetReconciledWorkflow() string {
	if x != nil && x.ReconciledWorkflow != nil {
		return *x.ReconciledWorkflow
	}
	return ""
}

func (x *UpdateSessionStatusRequest) GetKubeCrUid() string {
	if x != nil && x.KubeCrUid != nil {
		return *x.KubeCrUid
	}
	return ""
}

func (x *UpdateSessionStatusRequest) GetKubeNamespace() string {
	if x != nil && x.KubeNamespace != nil {
		return *x.KubeNamespace
	}
	return ""
}

type DeleteSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteSessionRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{6}
}

func (x *ListSessionsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListSessionsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*Session             `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Metadata      *ListMeta              `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{7}
}

func (x *ListSessionsResponse) GetItems() []*Session {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *ListSessionsResponse) GetMetadata() *ListMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{8}
}

type WatchSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSessionsRequest) Reset() {
	*x = WatchSessionsRequest{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSessionsRequest) ProtoMessage() {}

func (x *WatchSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSessionsRequest.ProtoReflect.Descriptor instead.
func (*WatchSessionsRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{9}
}

type SessionWatchEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          EventType              `protobuf:"varint,1,opt,name=type,proto3,enum=ambient.v1.EventType" json:"type,omitempty"`
	Session       *Session               `protobuf:"bytes,2,opt,name=session,proto3" json:"session,omitempty"`
	ResourceId    string                 `protobuf:"bytes,3,opt,name=resource_id,json=resourceId,proto3" json:"resource_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionWatchEvent) Reset() {
	*x = SessionWatchEvent{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionWatchEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionWatchEvent) ProtoMessage() {}

func (x *SessionWatchEvent) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionWatchEvent.ProtoReflect.Descriptor instead.
func (*SessionWatchEvent) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{10}
}

func (x *SessionWatchEvent) GetType() EventType {
	if x != nil {
		return x.Type
	}
	return EventType_EVENT_TYPE_UNSPECIFIED
}

func (x *SessionWatchEvent) GetSession() *Session {
	if x != nil {
		return x.Session
	}
	return nil
}

func (x *SessionWatchEvent) GetResourceId() string {
	if x != nil {
		return x.ResourceId
	}
	return ""
}

type SessionMessage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SessionId     string                 `protobuf:"bytes,2,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	Seq           int64                  `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	EventType     string                 `protobuf:"bytes,4,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       string                 `protobuf:"bytes,5,opt,name=payload,proto3" json:"payload,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionMessage) Reset() {
	*x = SessionMessage{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionMessage) ProtoMessage() {}

func (x *SessionMessage) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionMessage.ProtoReflect.Descriptor instead.
func (*SessionMessage) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{11}
}

func (x *SessionMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SessionMessage) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SessionMessage) GetSeq() int64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *SessionMessage) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *SessionMessage) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

func (x *SessionMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type PushSessionMessageRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	EventType     string                 `protobuf:"bytes,2,opt,name=event_type,json=eventType,proto3" json:"event_type,omitempty"`
	Payload       string                 `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PushSessionMessageRequest) Reset() {
	*x = PushSessionMessageRequest{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PushSessionMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PushSessionMessageRequest) ProtoMessage() {}

func (x *PushSessionMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PushSessionMessageRequest.ProtoReflect.Descriptor instead.
func (*PushSessionMessageRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{12}
}

func (x *PushSessionMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *PushSessionMessageRequest) GetEventType() string {
	if x != nil {
		return x.EventType
	}
	return ""
}

func (x *PushSessionMessageRequest) GetPayload() string {
	if x != nil {
		return x.Payload
	}
	return ""
}

type WatchSessionMessagesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	AfterSeq      int64                  `protobuf:"varint,2,opt,name=after_seq,json=afterSeq,proto3" json:"after_seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WatchSessionMessagesRequest) Reset() {
	*x = WatchSessionMessagesRequest{}
	mi := &file_ambient_v1_sessions_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WatchSessionMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WatchSessionMessagesRequest) ProtoMessage() {}

func (x *WatchSessionMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_ambient_v1_sessions_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WatchSessionMessagesRequest.ProtoReflect.Descriptor instead.
func (*WatchSessionMessagesRequest) Descriptor() ([]byte, []int) {
	return file_ambient_v1_sessions_proto_rawDescGZIP(), []int{13}
}

func (x *WatchSessionMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *WatchSessionMessagesRequest) GetAfterSeq() int64 {
	if x != nil {
		return x.AfterSeq
	}
	return 0
}

var File_ambient_v1_sessions_proto protoreflect.FileDescriptor

const file_ambient_v1_sessions_proto_rawDesc = "" +
	"\n" +
	"\x19ambient/v1/sessions.proto\x12\n" +
	"ambient.v1\x1a\x17ambient/v1/common.proto\x1a\x1fgoogle/protobuf/timestamp.proto\"\x94\x0f\n" +
	"\aSession\x127\n" +
	"\bmetadata\x18\x01 \x01(\v2\x1b.ambient.v1.ObjectReferenceR\bmetadata\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1e\n" +
	"\brepo_url\x18\x03 \x01(\tH\x00R\arepoUrl\x88\x01\x01\x12\x1b\n" +
	"\x06prompt\x18\x04 \x01(\tH\x01R\x06prompt\x88\x01\x01\x120\n" +
	"\x12created_by_user_id\x18\x05 \x01(\tH\x02R\x0fcreatedByUserId\x88\x01\x01\x12-\n" +
	"\x10assigned_user_id\x18\x06 \x01(\tH\x03R\x0eassignedUserId\x88\x01\x01\x12$\n" +
	"\vworkflow_id\x18\a \x01(\tH\x04R\n" +
	"workflowId\x88\x01\x01\x12\x19\n" +
	"\x05repos\x18\b \x01(\tH\x05R\x05repos\x88\x01\x01\x12\x1d\n" +
	"\atimeout\x18\n" +
	" \x01(\x05H\x06R\atimeout\x88\x01\x01\x12 \n" +
	"\tllm_model\x18\v \x01(\tH\aR\bllmModel\x88\x01\x01\x12,\n" +
	"\x0fllm_temperature\x18\f \x01(\x01H\bR\x0ellmTemperature\x88\x01\x01\x12)\n" +
	"\x0ellm_max_tokens\x18\r \x01(\x05H\tR\fllmMaxTokens\x88\x01\x01\x12/\n" +
	"\x11parent_session_id\x18\x0e \x01(\tH\n" +
	"R\x0fparentSessionId\x88\x01\x01\x12-\n" +
	"\x10bot_account_name\x18\x0f \x01(\tH\vR\x0ebotAccountName\x88\x01\x01\x122\n" +
	"\x12resource_overrides\x18\x10 \x01(\tH\fR\x11resourceOverrides\x88\x01\x01\x128\n" +
	"\x15environment_variables\x18\x11 \x01(\tH\rR\x14environmentVariables\x88\x01\x01\x12\x1b\n" +
	"\x06labels\x18\x12 \x01(\tH\x0eR\x06labels\x88\x01\x01\x12%\n" +
	"\vannotations\x18\x13 \x01(\tH\x0fR\vannotations\x88\x01\x01\x12\"\n" +
	"\n" +
	"project_id\x18\x14 \x01(\tH\x10R\tprojectId\x88\x01\x01\x12\x19\n" +
	"\x05phase\x18\x15 \x01(\tH\x11R\x05phase\x88\x01\x01\x12>\n" +
	"\n" +
	"start_time\x18\x16 \x01(\v2\x1a.google.protobuf.TimestampH\x12R\tstartTime\x88\x01\x01\x12H\n" +
	"\x0fcompletion_time\x18\x17 \x01(\v2\x1a.google.protobuf.TimestampH\x13R\x0ecompletionTime\x88\x01\x01\x12)\n" +
	"\x0esdk_session_id\x18\x18 \x01(\tH\x14R\fsdkSessionId\x88\x01\x01\x12/\n" +
	"\x11sdk_restart_count\x18\x19 \x01(\x05H\x15R\x0fsdkRestartCount\x88\x01\x01\x12#\n" +
	"\n" +
	"conditions\x18\x1a \x01(\tH\x16R\n" +
	"conditions\x88\x01\x01\x12.\n" +
	"\x10reconciled_repos\x18\x1b \x01(\tH\x17R\x0freconciledRepos\x88\x01\x01\x124\n" +
	"\x13reconciled_workflow\x18\x1c \x01(\tH\x18R\x12reconciledWorkflow\x88\x01\x01\x12%\n" +
	"\fkube_cr_name\x18\x1d \x01(\tH\x19R\n" +
	"kubeCrName\x88\x01\x01\x12#\n" +
	"\vkube_cr_uid\x18\x1e \x01(\tH\x1aR\tkubeCrUid\x88\x01\x01\x12*\n" +
	"\x0ekube_namespace\x18\x1f \x01(\tH\x1bR\rkubeNamespace\x88\x01\x01\x12\x1e\n" +
	"\bagent_id\x18  \x01(\tH\x1cR\aagentId\x88\x01\x01\x12I\n" +
	"\x10last_activity_at\x18! \x01(\v2\x1a.google.protobuf.TimestampH\x1dR\x0elastActivityAt\x88\x01\x01B\v\n" +
	"\t_repo_urlB\t\n" +
	"\a_promptB\x15\n" +
	"\x13_created_by_user_idB\x13\n" +
	"\x11_assigned_user_idB\x0e\n" +
	"\f_workflow_idB\b\n" +
	"\x06_reposB\n" +
	"\n" +
	"\b_timeoutB\f\n" +
	"\n" +
	"_llm_modelB\x12\n" +
	"\x10_llm_temperatureB\x11\n" +
	"\x0f_llm_max_tokensB\x14\n" +
	"\x12_parent_session_idB\x13\n" +
	"\x11_bot_account_nameB\x15\n" +
	"\x13_resource_overridesB\x18\n" +
	"\x16_environment_variablesB\t\n" +
	"\a_labelsB\x0e\n" +
	"\f_annotationsB\r\n" +
	"\v_project_idB\b\n" +
	"\x06_phaseB\r\n" +
	"\v_start_timeB\x12\n" +
	"\x10_completion_timeB\x11\n" +
	"\x0f_sdk_session_idB\x14\n" +
	"\x12_sdk_restart_countB\r\n" +
	"\v_conditionsB\x13\n" +
	"\x11_reconciled_reposB\x16\n" +
	"\x14_reconciled_workflowB\x0f\n" +
	"\r_kube_cr_nameB\x0e\n" +
	"\f_kube_cr_uidB\x11\n" +
	"\x0f_kube_namespaceB\v\n" +
	"\t_agent_idB\x13\n" +
	"\x11_last_activity_atJ\x04\b\t\x10\n" +
	"R\vinteractive\"\x91\b\n" +
	"\x14CreateSessionRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1e\n" +
	"\brepo_url\x18\x02 \x01(\tH\x00R\arepoUrl\x88\x01\x01\x12\x1b\n" +
	"\x06prompt\x18\x03 \x01(\tH\x01R\x06prompt\x88\x01\x01\x120\n" +
	"\x12created_by_user_id\x18\x04 \x01(\tH\x02R\x0fcreatedByUserId\x88\x01\x01\x12-\n" +
	"\x10assigned_user_id\x18\x05 \x01(\tH\x03R\x0eassignedUserId\x88\x01\x01\x12$\n" +
	"\vworkflow_id\x18\x06 \x01(\tH\x04R\n" +
	"workflowId\x88\x01\x01\x12\x19\n" +
	"\x05repos\x18\a \x01(\tH\x05R\x05repos\x88\x01\x01\x12\x1d\n" +
	"\atimeout\x18\t \x01(\x05H\x06R\atimeout\x88\x01\x01\x12 \n" +
	"\tllm_model\x18\n" +
	" \x01(\tH\aR\bllmModel\x88\x01\x01\x12,\n" +
	"\x0fllm_temperature\x18\v \x01(\x01H\bR\x0ellmTemperature\x88\x01\x01\x12)\n" +
	"\x0ellm_max_tokens\x18\f \x01(\x05H\tR\fllmMaxTokens\x88\x01\x01\x12/\n" +
	"\x11parent_session_id\x18\r \x01(\tH\n" +
	"R\x0fparentSessionId\x88\x01\x01\x12-\n" +
	"\x10bot_account_name\x18\x0e \x01(\tH\vR\x0ebotAccountName\x88\x01\x01\x122\n" +
	"\x12resource_overrides\x18\x0f \x01(\tH\fR\x11resourceOverrides\x88\x01\x01\x128\n" +
	"\x15environment_variables\x18\x10 \x01(\tH\rR\x14environmentVariables\x88\x01\x01\x12\x1b\n" +
	"\x06labels\x18\x11 \x01(\tH\x0eR\x06labels\x88\x01\x01\x12%\n" +
	"\vannotations\x18\x12 \x01(\tH\x0fR\vannotations\x88\x01\x01\x12\"\n" +
	"\n" +
	"project_id\x18\x13 \x01(\tH\x10R\tprojectId\x88\x01\x01B\v\n" +
	"\t_repo_urlB\t\n" +
	"\a_promptB\x15\n" +
	"\x13_created_by_user_idB\x13\n" +
	"\x11_assigned_user_idB\x0e\n" +
	"\f_workflow_idB\b\n" +
	"\x06_reposB\n" +
	"\n" +
	"\b_timeoutB\f\n" +
	"\n" +
	"_llm_modelB\x12\n" +
	"\x10_llm_temperatureB\x11\n" +
	"\x0f_llm_max_tokensB\x14\n" +
	"\x12_parent_session_idB\x13\n" +
	"\x11_bot_account_nameB\x15\n" +
	"\x13_resource_overridesB\x18\n" +
	"\x16_environment_variablesB\t\n" +
	"\a_labelsB\x0e\n" +
	"\f_annotationsB\r\n" +
	"\v_project_idJ\x04\b\b\x10\tR\vinteractive\"#\n" +
	"\x11GetSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"\xe6\a\n" +
	"\x14UpdateSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12\x1e\n" +
	"\brepo_url\x18\x03 \x01(\tH\x01R\arepoUrl\x88\x01\x01\x12\x1b\n" +
	"\x06prompt\x18\x04 \x01(\tH\x02R\x06prompt\x88\x01\x01\x12-\n" +
	"\x10assigned_user_id\x18\x05 \x01(\tH\x03R\x0eassignedUserId\x88\x01\x01\x12$\n" +
	"\vworkflow_id\x18\x06 \x01(\tH\x04R\n" +
	"workflowId\x88\x01\x01\x12\x19\n" +
	"\x05repos\x18\a \x01(\tH\x05R\x05repos\x88\x01\x01\x12\x1d\n" +
	"\atimeout\x18\t \x01(\x05H\x06R\atimeout\x88\x01\x01\x12 \n" +
	"\tllm_model\x18\n" +
	" \x01(\tH\aR\bllmModel\x88\x01\x01\x12,\n" +
	"\x0fllm_temperature\x18\v \x01(\x01H\bR\x0ellmTemperature\x88\x01\x01\x12)\n" +
	"\x0ellm_max_tokens\x18\f \x01(\x05H\tR\fllmMaxTokens\x88\x01\x01\x12/\n" +
	"\x11parent_session_id\x18\r \x01(\tH\n" +
	"R\x0fparentSessionId\x88\x01\x01\x12-\n" +
	"\x10bot_account_name\x18\x0e \x01(\tH\vR\x0ebotAccountName\x88\x01\x01\x122\n" +
	"\x12resource_overrides\x18\x0f \x01(\tH\fR\x11resourceOverrides\x88\x01\x01\x128\n" +
	"\x15environment_variables\x18\x10 \x01(\tH\rR\x14environmentVariables\x88\x01\x01\x12\x1b\n" +
	"\x06labels\x18\x11 \x01(\tH\x0eR\x06labels\x88\x01\x01\x12%\n" +
	"\vannotations\x18\x12 \x01(\tH\x0fR\vannotations\x88\x01\x01\x12\"\n" +
	"\n" +
	"project_id\x18\x13 \x01(\tH\x10R\tprojectId\x88\x01\x01B\a\n" +
	"\x05_nameB\v\n" +
	"\t_repo_urlB\t\n" +
	"\a_promptB\x13\n" +
	"\x11_assigned_user_idB\x0e\n" +
	"\f_workflow_idB\b\n" +
	"\x06_reposB\n" +
	"\n" +
	"\b_timeoutB\f\n" +
	"\n" +
	"_llm_modelB\x12\n" +
	"\x10_llm_temperatureB\x11\n" +
	"\x0f_llm_max_tokensB\x14\n" +
	"\x12_parent_session_idB\x13\n" +
	"\x11_bot_account_nameB\x15\n" +
	"\x13_resource_overridesB\x18\n" +
	"\x16_environment_variablesB\t\n" +
	"\a_labelsB\x0e\n" +
	"\f_annotationsB\r\n" +
	"\v_project_idJ\x04\b\b\x10\tR\vinteractive\"\xbe\x05\n" +
	"\x1aUpdateSessionStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\x05phase\x18\x02 \x01(\tH\x00R\x05phase\x88\x01\x01\x12>\n" +
	"\n" +
	"start_time\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampH\x01R\tstartTime\x88\x01\x01\x12H\n" +
	"\x0fcompletion_time\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x0ecompletionTime\x88\x01\x01\x12)\n" +
	"\x0esdk_session_id\x18\x05 \x01(\tH\x03R\fsdkSessionId\x88\x01\x01\x12/\n" +
	"\x11sdk_restart_count\x18\x06 \x01(\x05H\x04R\x0fsdkRestartCount\x88\x01\x01\x12#\n" +
	"\n" +
	"conditions\x18\a \x01(\tH\x05R\n" +
	"conditions\x88\x01\x01\x12.\n" +
	"\x10reconciled_repos\x18\b \x01(\tH\x06R\x0freconciledRepos\x88\x01\x01\x124\n" +
	"\x13reconciled_workflow\x18\t \x01(\tH\aR\x12reconciledWorkflow\x88\x01\x01\x12#\n" +
	"\vkube_cr_uid\x18\n" +
	" \x01(\tH\bR\tkubeCrUid\x88\x01\x01\x12*\n" +
	"\x0ekube_namespace\x18\v \x01(\tH\tR\rkubeNamespace\x88\x01\x01B\b\n" +
	"\x06_phaseB\r\n" +
	"\v_start_timeB\x12\n" +
	"\x10_completion_timeB\x11\n" +
	"\x0f_sdk_session_idB\x14\n" +
	"\x12_sdk_restart_countB\r\n" +
	"\v_conditionsB\x13\n" +
	"\x11_reconciled_reposB\x16\n" +
	"\x14_reconciled_workflowB\x0e\n" +
	"\f_kube_cr_uidB\x11\n" +
	"\x0f_kube_namespace\"&\n" +
	"\x14DeleteSessionRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"=\n" +
	"\x13ListSessionsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\"s\n" +
	"\x14ListSessionsResponse\x12)\n" +
	"\x05items\x18\x01 \x03(\v2\x13.ambient.v1.SessionR\x05items\x120\n" +
	"\bmetadata\x18\x02 \x01(\v2\x14.ambient.v1.ListMetaR\bmetadata\"\x17\n" +
	"\x15DeleteSessionResponse\"\x16\n" +
	"\x14WatchSessionsRequest\"\x8e\x01\n" +
	"\x11SessionWatchEvent\x12)\n" +
	"\x04type\x18\x01 \x01(\x0e2\x15.ambient.v1.EventTypeR\x04type\x12-\n" +
	"\asession\x18\x02 \x01(\v2\x13.ambient.v1.SessionR\asession\x12\x1f\n" +
	"\vresource_id\x18\x03 \x01(\tR\n" +
	"resourceId\"\xc5\x01\n" +
	"\x0eSessionMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1d\n" +
	"\n" +
	"session_id\x18\x02 \x01(\tR\tsessionId\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x03R\x03seq\x12\x1d\n" +
	"\n" +
	"event_type\x18\x04 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x05 \x01(\tR\apayload\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"s\n" +
	"\x19PushSessionMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1d\n" +
	"\n" +
	"event_type\x18\x02 \x01(\tR\teventType\x12\x18\n" +
	"\apayload\x18\x03 \x01(\tR\apayload\"Y\n" +
	"\x1bWatchSessionMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x1b\n" +
	"\tafter_seq\x18\x02 \x01(\x03R\bafterSeq2\xeb\x05\n" +
	"\x0eSessionService\x12@\n" +
	"\n" +
	"GetSession\x12\x1d.ambient.v1.GetSessionRequest\x1a\x13.ambient.v1.Session\x12F\n" +
	"\rCreateSession\x12 .ambient.v1.CreateSessionRequest\x1a\x13.ambient.v1.Session\x12F\n" +
	"\rUpdateSession\x12 .ambient.v1.UpdateSessionRequest\x1a\x13.ambient.v1.Session\x12R\n" +
	"\x13UpdateSessionStatus\x12&.ambient.v1.UpdateSessionStatusRequest\x1a\x13.ambient.v1.Session\x12T\n" +
	"\rDeleteSession\x12 .ambient.v1.DeleteSessionRequest\x1a!.ambient.v1.DeleteSessionResponse\x12Q\n" +
	"\fListSessions\x12\x1f.ambient.v1.ListSessionsRequest\x1a .ambient.v1.ListSessionsResponse\x12R\n" +
	"\rWatchSessions\x12 .ambient.v1.WatchSessionsRequest\x1a\x1d.ambient.v1.SessionWatchEvent0\x01\x12W\n" +
	"\x12PushSessionMessage\x12%.ambient.v1.PushSessionMessageRequest\x1a\x1a.ambient.v1.SessionMessage\x12]\n" +
	"\x14WatchSessionMessages\x12'.ambient.v1.WatchSessionMessagesRequest\x1a\x1a.ambient.v1.SessionMessage0\x01BcZagithub.com/ambient-code/platform/components/ambient-api-server/pkg/api/grpc/ambient/v1;ambient_v1b\x06proto3"

var (
	file_ambient_v1_sessions_proto_rawDescOnce sync.Once
	file_ambient_v1_sessions_proto_rawDescData []byte
)

func file_ambient_v1_sessions_proto_rawDescGZIP() []byte {
	file_ambient_v1_sessions_proto_rawDescOnce.Do(func() {
		file_ambient_v1_sessions_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_ambient_v1_sessions_proto_rawDesc), len(file_ambient_v1_sessions_proto_rawDesc)))
	})
	return file_ambient_v1_sessions_proto_rawDescData
}

var file_ambient_v1_sessions_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_ambient_v1_sessions_proto_goTypes = []any{
	(*Session)(nil),                     // 0: ambient.v1.Session
	(*CreateSessionRequest)(nil),        // 1: ambient.v1.CreateSessionRequest
	(*GetSessionRequest)(nil),           // 2: ambient.v1.GetSessionRequest
	(*UpdateSessionRequest)(nil),        // 3: ambient.v1.UpdateSessionRequest
	(*UpdateSessionStatusRequest)(nil),  // 4: ambient.v1.UpdateSessionStatusRequest
	(*DeleteSessionRequest)(nil),        // 5: ambient.v1.DeleteSessionRequest
	(*ListSessionsRequest)(nil),         // 6: ambient.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),        // 7: ambient.v1.ListSessionsResponse
	(*DeleteSessionResponse)(nil),       // 8: ambient.v1.DeleteSessionResponse
	(*WatchSessionsRequest)(nil),        // 9: ambient.v1.WatchSessionsRequest
	(*SessionWatchEvent)(nil),           // 10: ambient.v1.SessionWatchEvent
	(*SessionMessage)(nil),              // 11: ambient.v1.SessionMessage
	(*PushSessionMessageRequest)(nil),   // 12: ambient.v1.PushSessionMessageRequest
	(*WatchSessionMessagesRequest)(nil), // 13: ambient.v1.WatchSessionMessagesRequest
	(*ObjectReference)(nil),             // 14: ambient.v1.ObjectReference
	(*timestamppb.Timestamp)(nil),       // 15: google.protobuf.Timestamp
	(*ListMeta)(nil),                    // 16: ambient.v1.ListMeta
	(EventType)(0),                      // 17: ambient.v1.EventType
}
var file_ambient_v1_sessions_proto_depIdxs = []int32{
	14, // 0: ambient.v1.Session.metadata:type_name -> ambient.v1.ObjectReference
	15, // 1: ambient.v1.Session.start_time:type_name -> google.protobuf.Timestamp
	15, // 2: ambient.v1.Session.completion_time:type_name -> google.protobuf.Timestamp
	15, // 3: ambient.v1.Session.last_activity_at:type_name -> google.protobuf.Timestamp
	15, // 4: ambient.v1.UpdateSessionStatusRequest.start_time:type_name -> google.protobuf.Timestamp
	15, // 5: ambient.v1.UpdateSessionStatusRequest.completion_time:type_name -> google.protobuf.Timestamp
	0,  // 6: ambient.v1.ListSessionsResponse.items:type_name -> ambient.v1.Session
	16, // 7: ambient.v1.ListSessionsResponse.metadata:type_name -> ambient.v1.ListMeta
	17, // 8: ambient.v1.SessionWatchEvent.type:type_name -> ambient.v1.EventType
	0,  // 9: ambient.v1.SessionWatchEvent.session:type_name -> ambient.v1.Session
	15, // 10: ambient.v1.SessionMessage.created_at:type_name -> google.protobuf.Timestamp
	2,  // 11: ambient.v1.SessionService.GetSession:input_type -> ambient.v1.GetSessionRequest
	1,  // 12: ambient.v1.SessionService.CreateSession:input_type -> ambient.v1.CreateSessionRequest
	3,  // 13: ambient.v1.SessionService.UpdateSession:input_type -> ambient.v1.UpdateSessionRequest
	4,  // 14: ambient.v1.SessionService.UpdateSessionStatus:input_type -> ambient.v1.UpdateSessionStatusRequest
	5,  // 15: ambient.v1.SessionService.DeleteSession:input_type -> ambient.v1.DeleteSessionRequest
	6,  // 16: ambient.v1.SessionService.ListSessions:input_type -> ambient.v1.ListSessionsRequest
	9,  // 17: ambient.v1.SessionService.WatchSessions:input_type -> ambient.v1.WatchSessionsRequest
	12, // 18: ambient.v1.SessionService.PushSessionMessage:input_type -> ambient.v1.PushSessionMessageRequest
	13, // 19: ambient.v1.SessionService.WatchSessionMessages:input_type -> ambient.v1.WatchSessionMessagesRequest
	0,  // 20: ambient.v1.SessionService.GetSession:output_type -> ambient.v1.Session
	0,  // 21: ambient.v1.SessionService.CreateSession:output_type -> ambient.v1.Session
	0,  // 22: ambient.v1.SessionService.UpdateSession:output_type -> ambient.v1.Session
	0,  // 23: ambient.v1.SessionService.UpdateSessionStatus:output_type -> ambient.v1.Session
	8,  // 24: ambient.v1.SessionService.DeleteSession:output_type -> ambient.v1.DeleteSessionResponse
	7,  // 25: ambient.v1.SessionService.ListSessions:output_type -> ambient.v1.ListSessionsResponse
	10, // 26: ambient.v1.SessionService.WatchSessions:output_type -> ambient.v1.SessionWatchEvent
	11, // 27: ambient.v1.SessionService.PushSessionMessage:output_type -> ambient.v1.SessionMessage
	11, // 28: ambient.v1.SessionService.WatchSessionMessages:output_type -> ambient.v1.SessionMessage
	20, // [20:29] is the sub-list for method output_type
	11, // [11:20] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_ambient_v1_sessions_proto_init() }
func file_ambient_v1_sessions_proto_init() {
	if File_ambient_v1_sessions_proto != nil {
		return
	}
	file_ambient_v1_common_proto_init()
	file_ambient_v1_sessions_proto_msgTypes[0].OneofWrappers = []any{}
	file_ambient_v1_sessions_proto_msgTypes[1].OneofWrappers = []any{}
	file_ambient_v1_sessions_proto_msgTypes[3].OneofWrappers = []any{}
	file_ambient_v1_sessions_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_ambient_v1_sessions_proto_rawDesc), len(file_ambient_v1_sessions_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_ambient_v1_sessions_proto_goTypes,
		DependencyIndexes: file_ambient_v1_sessions_proto_depIdxs,
		MessageInfos:      file_ambient_v1_sessions_proto_msgTypes,
	}.Build()
	File_ambient_v1_sessions_proto = out.File
	file_ambient_v1_sessions_proto_goTypes = nil
	file_ambient_v1_sessions_proto_depIdxs = nil
}
