// SPDX-FileCopyrightText: Copyright (c) 2025-2026 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//
// Vendored from github.com/NVIDIA/OpenShell/proto/datamodel.proto at 420a855ddc21a20ac528f902bd2ed7f3fc133dc9

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openshell/datamodel/v1/datamodel.proto

package datamodel_v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Kubernetes-style metadata shared by all top-level OpenShell domain objects.
//
// This structure provides consistent metadata (identity, labels, timestamps,
// resource versioning) across Sandbox, Provider, SshSession, and other resources.
type ObjectMeta struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stable object ID generated by the gateway.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// Human-readable object name (unique per object type).
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// Milliseconds since Unix epoch when the object was created.
	CreatedAtMs int64 `protobuf:"varint,3,opt,name=created_at_ms,json=createdAtMs,proto3" json:"created_at_ms,omitempty"`
	// Key-value labels for filtering and organization.
	// Labels must follow Kubernetes conventions: alphanumeric + `-._/`, max 63 chars per segment.
	Labels map[string]string `protobuf:"bytes,4,rep,name=labels,proto3" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Optimistic concurrency control version.
	// Incremented by the gateway on each update. Clients can use this for compare-and-swap operations.
	ResourceVersion uint64 `protobuf:"varint,5,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *ObjectMeta) Reset() {
	*x = ObjectMeta{}
	mi := &file_openshell_datamodel_v1_datamodel_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObjectMeta) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObjectMeta) ProtoMessage() {}

func (x *ObjectMeta) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_datamodel_v1_datamodel_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObjectMeta.ProtoReflect.Descriptor instead.
func (*ObjectMeta) Descriptor() ([]byte, []int) {
	return file_openshell_datamodel_v1_datamodel_proto_rawDescGZIP(), []int{0}
}

func (x *ObjectMeta) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ObjectMeta) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ObjectMeta) GetCreatedAtMs() int64 {
	if x != nil {
		return x.CreatedAtMs
	}
	return 0
}

func (x *ObjectMeta) GetLabels() map[string]string {
	if x != nil {
		return x.Labels
	}
	return nil
}

func (x *ObjectMeta) GetResourceVersion() uint64 {
	if x != nil {
		return x.ResourceVersion
	}
	return 0
}

// Provider model stored by OpenShell.
type Provider struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Kubernetes-style metadata (id, name, labels, timestamps, resource version).
	Metadata *ObjectMeta `protobuf:"bytes,1,opt,name=metadata,proto3" json:"metadata,omitempty"`
	// Canonical provider type slug (for example: "claude", "gitlab").
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// Secret values used for authentication.
	Credentials map[string]string `protobuf:"bytes,3,rep,name=credentials,proto3" json:"credentials,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Non-secret provider configuration.
	Config map[string]string `protobuf:"bytes,4,rep,name=config,proto3" json:"config,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	// Expiration timestamps for credential values, keyed by credential/env var
	// name. A zero or missing value means the credential does not expire.
	CredentialExpiresAtMs map[string]int64 `protobuf:"bytes,5,rep,name=credential_expires_at_ms,json=credentialExpiresAtMs,proto3" json:"credential_expires_at_ms,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"varint,2,opt,name=value"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Provider) Reset() {
	*x = Provider{}
	mi := &file_openshell_datamodel_v1_datamodel_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Provider) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Provider) ProtoMessage() {}

func (x *Provider) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_datamodel_v1_datamodel_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Provider.ProtoReflect.Descriptor instead.
func (*Provider) Descriptor() ([]byte, []int) {
	return file_openshell_datamodel_v1_datamodel_proto_rawDescGZIP(), []int{1}
}

func (x *Provider) GetMetadata() *ObjectMeta {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Provider) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Provider) GetCredentials() map[string]string {
	if x != nil {
		return x.Credentials
	}
	return nil
}

func (x *Provider) GetConfig() map[string]string {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Provider) GetCredentialExpiresAtMs() map[string]int64 {
	if x != nil {
		return x.CredentialExpiresAtMs
	}
	return nil
}

var File_openshell_datamodel_v1_datamodel_proto protoreflect.FileDescriptor

const file_openshell_datamodel_v1_datamodel_proto_rawDesc = "" +
	"\n" +
	"&openshell/datamodel/v1/datamodel.proto\x12\x16openshell.datamodel.v1\"\x82\x02\n" +
	"\n" +
	"ObjectMeta\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\"\n" +
	"\rcreated_at_ms\x18\x03 \x01(\x03R\vcreatedAtMs\x12F\n" +
	"\x06labels\x18\x04 \x03(\v2..openshell.datamodel.v1.ObjectMeta.LabelsEntryR\x06labels\x12)\n" +
	"\x10resource_version\x18\x05 \x01(\x04R\x0fresourceVersion\x1a9\n" +
	"\vLabelsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xb4\x04\n" +
	"\bProvider\x12>\n" +
	"\bmetadata\x18\x01 \x01(\v2\".openshell.datamodel.v1.ObjectMetaR\bmetadata\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12S\n" +
	"\vcredentials\x18\x03 \x03(\v21.openshell.datamodel.v1.Provider.CredentialsEntryR\vcredentials\x12D\n" +
	"\x06config\x18\x04 \x03(\v2,.openshell.datamodel.v1.Provider.ConfigEntryR\x06config\x12t\n" +
	"\x18credential_expires_at_ms\x18\x05 \x03(\v2;.openshell.datamodel.v1.Provider.CredentialExpiresAtMsEntryR\x15credentialExpiresAtMs\x1a>\n" +
	"\x10CredentialsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1a9\n" +
	"\vConfigEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\x1aH\n" +
	"\x1aCredentialExpiresAtMsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\x03R\x05value:\x028\x01B\x7fZ}github.com/ambient-code/platform/components/ambient-control-plane/internal/openshell/grpc/openshell/datamodel/v1;datamodel_v1b\x06proto3"

var (
	file_openshell_datamodel_v1_datamodel_proto_rawDescOnce sync.Once
	file_openshell_datamodel_v1_datamodel_proto_rawDescData []byte
)

func file_openshell_datamodel_v1_datamodel_proto_rawDescGZIP() []byte {
	file_openshell_datamodel_v1_datamodel_proto_rawDescOnce.Do(func() {
		file_openshell_datamodel_v1_datamodel_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshell_datamodel_v1_datamodel_proto_rawDesc), len(file_openshell_datamodel_v1_datamodel_proto_rawDesc)))
	})
	return file_openshell_datamodel_v1_datamodel_proto_rawDescData
}

var file_openshell_datamodel_v1_datamodel_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_openshell_datamodel_v1_datamodel_proto_goTypes = []any{
	(*ObjectMeta)(nil), // 0: openshell.datamodel.v1.ObjectMeta
	(*Provider)(nil),   // 1: openshell.datamodel.v1.Provider
	nil,                // 2: openshell.datamodel.v1.ObjectMeta.LabelsEntry
	nil,                // 3: openshell.datamodel.v1.Provider.CredentialsEntry
	nil,                // 4: openshell.datamodel.v1.Provider.ConfigEntry
	nil,                // 5: openshell.datamodel.v1.Provider.CredentialExpiresAtMsEntry
}
var file_openshell_datamodel_v1_datamodel_proto_depIdxs = []int32{
	2, // 0: openshell.datamodel.v1.ObjectMeta.labels:type_name -> openshell.datamodel.v1.ObjectMeta.LabelsEntry
	0, // 1: openshell.datamodel.v1.Provider.metadata:type_name -> openshell.datamodel.v1.ObjectMeta
	3, // 2: openshell.datamodel.v1.Provider.credentials:type_name -> openshell.datamodel.v1.Provider.CredentialsEntry
	4, // 3: openshell.datamodel.v1.Provider.config:type_name -> openshell.datamodel.v1.Provider.ConfigEntry
	5, // 4: openshell.datamodel.v1.Provider.credential_expires_at_ms:type_name -> openshell.datamodel.v1.Provider.CredentialExpiresAtMsEntry
	5, // [5:5] is the sub-list for method output_type
	5, // [5:5] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_openshell_datamodel_v1_datamodel_proto_init() }
func file_openshell_datamodel_v1_datamodel_proto_init() {
	if File_openshell_datamodel_v1_datamodel_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshell_datamodel_v1_datamodel_proto_rawDesc), len(file_openshell_datamodel_v1_datamodel_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_openshell_datamodel_v1_datamodel_proto_goTypes,
		DependencyIndexes: file_openshell_datamodel_v1_datamodel_proto_depIdxs,
		MessageInfos:      file_openshell_datamodel_v1_datamodel_proto_msgTypes,
	}.Build()
	File_openshell_datamodel_v1_datamodel_proto = out.File
	file_openshell_datamodel_v1_datamodel_proto_goTypes = nil
	file_openshell_datamodel_v1_datamodel_proto_depIdxs = nil
}
