kind: Kustomization
resources:
  - ../../base
  - project.yaml
  - provider-vertex.yaml
  - provider-jira.yaml
  - provider-github.yaml
  - credential-vertex.yaml
  - credential-jira.yaml
  - credential-github.yaml
