/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the AgentPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &AgentPatchRequest{}

// AgentPatchRequest struct for AgentPatchRequest
type AgentPatchRequest struct {
	Name        *string `json:"name,omitempty"`
	DisplayName *string `json:"display_name,omitempty"`
	Description *string `json:"description,omitempty"`
	// Update agent prompt (access controlled by RBAC)
	Prompt          *string            `json:"prompt,omitempty"`
	RepoUrl         *string            `json:"repo_url,omitempty"`
	LlmModel        *string            `json:"llm_model,omitempty"`
	LlmTemperature  *float64           `json:"llm_temperature,omitempty"`
	LlmMaxTokens    *int32             `json:"llm_max_tokens,omitempty"`
	Entrypoint      *string            `json:"entrypoint,omitempty"`
	Providers       []string           `json:"providers,omitempty"`
	Payloads        []Payload          `json:"payloads,omitempty"`
	Environment     *map[string]string `json:"environment,omitempty"`
	SandboxTemplate *SandboxTemplate   `json:"sandbox_template,omitempty"`
	SandboxPolicy   *string            `json:"sandbox_policy,omitempty"`
	Labels          *string            `json:"labels,omitempty"`
	Annotations     *string            `json:"annotations,omitempty"`
}

// NewAgentPatchRequest instantiates a new AgentPatchRequest object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewAgentPatchRequest() *AgentPatchRequest {
	this := AgentPatchRequest{}
	return &this
}

// NewAgentPatchRequestWithDefaults instantiates a new AgentPatchRequest object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewAgentPatchRequestWithDefaults() *AgentPatchRequest {
	this := AgentPatchRequest{}
	return &this
}

// GetName returns the Name field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetName() string {
	if o == nil || IsNil(o.Name) {
		var ret string
		return ret
	}
	return *o.Name
}

// GetNameOk returns a tuple with the Name field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetNameOk() (*string, bool) {
	if o == nil || IsNil(o.Name) {
		return nil, false
	}
	return o.Name, true
}

// HasName returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasName() bool {
	if o != nil && !IsNil(o.Name) {
		return true
	}

	return false
}

// SetName gets a reference to the given string and assigns it to the Name field.
func (o *AgentPatchRequest) SetName(v string) {
	o.Name = &v
}

// GetDisplayName returns the DisplayName field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetDisplayName() string {
	if o == nil || IsNil(o.DisplayName) {
		var ret string
		return ret
	}
	return *o.DisplayName
}

// GetDisplayNameOk returns a tuple with the DisplayName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetDisplayNameOk() (*string, bool) {
	if o == nil || IsNil(o.DisplayName) {
		return nil, false
	}
	return o.DisplayName, true
}

// HasDisplayName returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasDisplayName() bool {
	if o != nil && !IsNil(o.DisplayName) {
		return true
	}

	return false
}

// SetDisplayName gets a reference to the given string and assigns it to the DisplayName field.
func (o *AgentPatchRequest) SetDisplayName(v string) {
	o.DisplayName = &v
}

// GetDescription returns the Description field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetDescription() string {
	if o == nil || IsNil(o.Description) {
		var ret string
		return ret
	}
	return *o.Description
}

// GetDescriptionOk returns a tuple with the Description field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetDescriptionOk() (*string, bool) {
	if o == nil || IsNil(o.Description) {
		return nil, false
	}
	return o.Description, true
}

// HasDescription returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasDescription() bool {
	if o != nil && !IsNil(o.Description) {
		return true
	}

	return false
}

// SetDescription gets a reference to the given string and assigns it to the Description field.
func (o *AgentPatchRequest) SetDescription(v string) {
	o.Description = &v
}

// GetPrompt returns the Prompt field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetPrompt() string {
	if o == nil || IsNil(o.Prompt) {
		var ret string
		return ret
	}
	return *o.Prompt
}

// GetPromptOk returns a tuple with the Prompt field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetPromptOk() (*string, bool) {
	if o == nil || IsNil(o.Prompt) {
		return nil, false
	}
	return o.Prompt, true
}

// HasPrompt returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasPrompt() bool {
	if o != nil && !IsNil(o.Prompt) {
		return true
	}

	return false
}

// SetPrompt gets a reference to the given string and assigns it to the Prompt field.
func (o *AgentPatchRequest) SetPrompt(v string) {
	o.Prompt = &v
}

// GetRepoUrl returns the RepoUrl field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetRepoUrl() string {
	if o == nil || IsNil(o.RepoUrl) {
		var ret string
		return ret
	}
	return *o.RepoUrl
}

// GetRepoUrlOk returns a tuple with the RepoUrl field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetRepoUrlOk() (*string, bool) {
	if o == nil || IsNil(o.RepoUrl) {
		return nil, false
	}
	return o.RepoUrl, true
}

// HasRepoUrl returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasRepoUrl() bool {
	if o != nil && !IsNil(o.RepoUrl) {
		return true
	}

	return false
}

// SetRepoUrl gets a reference to the given string and assigns it to the RepoUrl field.
func (o *AgentPatchRequest) SetRepoUrl(v string) {
	o.RepoUrl = &v
}

// GetLlmModel returns the LlmModel field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLlmModel() string {
	if o == nil || IsNil(o.LlmModel) {
		var ret string
		return ret
	}
	return *o.LlmModel
}

// GetLlmModelOk returns a tuple with the LlmModel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLlmModelOk() (*string, bool) {
	if o == nil || IsNil(o.LlmModel) {
		return nil, false
	}
	return o.LlmModel, true
}

// HasLlmModel returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLlmModel() bool {
	if o != nil && !IsNil(o.LlmModel) {
		return true
	}

	return false
}

// SetLlmModel gets a reference to the given string and assigns it to the LlmModel field.
func (o *AgentPatchRequest) SetLlmModel(v string) {
	o.LlmModel = &v
}

// GetLlmTemperature returns the LlmTemperature field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLlmTemperature() float64 {
	if o == nil || IsNil(o.LlmTemperature) {
		var ret float64
		return ret
	}
	return *o.LlmTemperature
}

// GetLlmTemperatureOk returns a tuple with the LlmTemperature field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLlmTemperatureOk() (*float64, bool) {
	if o == nil || IsNil(o.LlmTemperature) {
		return nil, false
	}
	return o.LlmTemperature, true
}

// HasLlmTemperature returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLlmTemperature() bool {
	if o != nil && !IsNil(o.LlmTemperature) {
		return true
	}

	return false
}

// SetLlmTemperature gets a reference to the given float64 and assigns it to the LlmTemperature field.
func (o *AgentPatchRequest) SetLlmTemperature(v float64) {
	o.LlmTemperature = &v
}

// GetLlmMaxTokens returns the LlmMaxTokens field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLlmMaxTokens() int32 {
	if o == nil || IsNil(o.LlmMaxTokens) {
		var ret int32
		return ret
	}
	return *o.LlmMaxTokens
}

// GetLlmMaxTokensOk returns a tuple with the LlmMaxTokens field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLlmMaxTokensOk() (*int32, bool) {
	if o == nil || IsNil(o.LlmMaxTokens) {
		return nil, false
	}
	return o.LlmMaxTokens, true
}

// HasLlmMaxTokens returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLlmMaxTokens() bool {
	if o != nil && !IsNil(o.LlmMaxTokens) {
		return true
	}

	return false
}

// SetLlmMaxTokens gets a reference to the given int32 and assigns it to the LlmMaxTokens field.
func (o *AgentPatchRequest) SetLlmMaxTokens(v int32) {
	o.LlmMaxTokens = &v
}

// GetEntrypoint returns the Entrypoint field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetEntrypoint() string {
	if o == nil || IsNil(o.Entrypoint) {
		var ret string
		return ret
	}
	return *o.Entrypoint
}

// GetEntrypointOk returns a tuple with the Entrypoint field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetEntrypointOk() (*string, bool) {
	if o == nil || IsNil(o.Entrypoint) {
		return nil, false
	}
	return o.Entrypoint, true
}

// HasEntrypoint returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasEntrypoint() bool {
	if o != nil && !IsNil(o.Entrypoint) {
		return true
	}

	return false
}

// SetEntrypoint gets a reference to the given string and assigns it to the Entrypoint field.
func (o *AgentPatchRequest) SetEntrypoint(v string) {
	o.Entrypoint = &v
}

// GetProviders returns the Providers field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetProviders() []string {
	if o == nil || IsNil(o.Providers) {
		var ret []string
		return ret
	}
	return o.Providers
}

// GetProvidersOk returns a tuple with the Providers field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetProvidersOk() ([]string, bool) {
	if o == nil || IsNil(o.Providers) {
		return nil, false
	}
	return o.Providers, true
}

// HasProviders returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasProviders() bool {
	if o != nil && !IsNil(o.Providers) {
		return true
	}

	return false
}

// SetProviders gets a reference to the given []string and assigns it to the Providers field.
func (o *AgentPatchRequest) SetProviders(v []string) {
	o.Providers = v
}

// GetPayloads returns the Payloads field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetPayloads() []Payload {
	if o == nil || IsNil(o.Payloads) {
		var ret []Payload
		return ret
	}
	return o.Payloads
}

// GetPayloadsOk returns a tuple with the Payloads field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetPayloadsOk() ([]Payload, bool) {
	if o == nil || IsNil(o.Payloads) {
		return nil, false
	}
	return o.Payloads, true
}

// HasPayloads returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasPayloads() bool {
	if o != nil && !IsNil(o.Payloads) {
		return true
	}

	return false
}

// SetPayloads gets a reference to the given []Payload and assigns it to the Payloads field.
func (o *AgentPatchRequest) SetPayloads(v []Payload) {
	o.Payloads = v
}

// GetEnvironment returns the Environment field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetEnvironment() map[string]string {
	if o == nil || IsNil(o.Environment) {
		var ret map[string]string
		return ret
	}
	return *o.Environment
}

// GetEnvironmentOk returns a tuple with the Environment field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetEnvironmentOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Environment) {
		return nil, false
	}
	return o.Environment, true
}

// HasEnvironment returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasEnvironment() bool {
	if o != nil && !IsNil(o.Environment) {
		return true
	}

	return false
}

// SetEnvironment gets a reference to the given map[string]string and assigns it to the Environment field.
func (o *AgentPatchRequest) SetEnvironment(v map[string]string) {
	o.Environment = &v
}

// GetSandboxTemplate returns the SandboxTemplate field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetSandboxTemplate() SandboxTemplate {
	if o == nil || IsNil(o.SandboxTemplate) {
		var ret SandboxTemplate
		return ret
	}
	return *o.SandboxTemplate
}

// GetSandboxTemplateOk returns a tuple with the SandboxTemplate field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetSandboxTemplateOk() (*SandboxTemplate, bool) {
	if o == nil || IsNil(o.SandboxTemplate) {
		return nil, false
	}
	return o.SandboxTemplate, true
}

// HasSandboxTemplate returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasSandboxTemplate() bool {
	if o != nil && !IsNil(o.SandboxTemplate) {
		return true
	}

	return false
}

// SetSandboxTemplate gets a reference to the given SandboxTemplate and assigns it to the SandboxTemplate field.
func (o *AgentPatchRequest) SetSandboxTemplate(v SandboxTemplate) {
	o.SandboxTemplate = &v
}

// GetSandboxPolicy returns the SandboxPolicy field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetSandboxPolicy() string {
	if o == nil || IsNil(o.SandboxPolicy) {
		var ret string
		return ret
	}
	return *o.SandboxPolicy
}

// GetSandboxPolicyOk returns a tuple with the SandboxPolicy field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetSandboxPolicyOk() (*string, bool) {
	if o == nil || IsNil(o.SandboxPolicy) {
		return nil, false
	}
	return o.SandboxPolicy, true
}

// HasSandboxPolicy returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasSandboxPolicy() bool {
	if o != nil && !IsNil(o.SandboxPolicy) {
		return true
	}

	return false
}

// SetSandboxPolicy gets a reference to the given string and assigns it to the SandboxPolicy field.
func (o *AgentPatchRequest) SetSandboxPolicy(v string) {
	o.SandboxPolicy = &v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetLabels() string {
	if o == nil || IsNil(o.Labels) {
		var ret string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetLabelsOk() (*string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given string and assigns it to the Labels field.
func (o *AgentPatchRequest) SetLabels(v string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *AgentPatchRequest) GetAnnotations() string {
	if o == nil || IsNil(o.Annotations) {
		var ret string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *AgentPatchRequest) GetAnnotationsOk() (*string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *AgentPatchRequest) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given string and assigns it to the Annotations field.
func (o *AgentPatchRequest) SetAnnotations(v string) {
	o.Annotations = &v
}

func (o AgentPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o AgentPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Name) {
		toSerialize["name"] = o.Name
	}
	if !IsNil(o.DisplayName) {
		toSerialize["display_name"] = o.DisplayName
	}
	if !IsNil(o.Description) {
		toSerialize["description"] = o.Description
	}
	if !IsNil(o.Prompt) {
		toSerialize["prompt"] = o.Prompt
	}
	if !IsNil(o.RepoUrl) {
		toSerialize["repo_url"] = o.RepoUrl
	}
	if !IsNil(o.LlmModel) {
		toSerialize["llm_model"] = o.LlmModel
	}
	if !IsNil(o.LlmTemperature) {
		toSerialize["llm_temperature"] = o.LlmTemperature
	}
	if !IsNil(o.LlmMaxTokens) {
		toSerialize["llm_max_tokens"] = o.LlmMaxTokens
	}
	if !IsNil(o.Entrypoint) {
		toSerialize["entrypoint"] = o.Entrypoint
	}
	if !IsNil(o.Providers) {
		toSerialize["providers"] = o.Providers
	}
	if !IsNil(o.Payloads) {
		toSerialize["payloads"] = o.Payloads
	}
	if !IsNil(o.Environment) {
		toSerialize["environment"] = o.Environment
	}
	if !IsNil(o.SandboxTemplate) {
		toSerialize["sandbox_template"] = o.SandboxTemplate
	}
	if !IsNil(o.SandboxPolicy) {
		toSerialize["sandbox_policy"] = o.SandboxPolicy
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	return toSerialize, nil
}

type NullableAgentPatchRequest struct {
	value *AgentPatchRequest
	isSet bool
}

func (v NullableAgentPatchRequest) Get() *AgentPatchRequest {
	return v.value
}

func (v *NullableAgentPatchRequest) Set(val *AgentPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableAgentPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableAgentPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableAgentPatchRequest(val *AgentPatchRequest) *NullableAgentPatchRequest {
	return &NullableAgentPatchRequest{value: val, isSet: true}
}

func (v NullableAgentPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableAgentPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
