/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.
// NOTE: Manually updated to match openapi.roleBindings.yaml typed-FK schema (2026-05-13).
// Run `make generate` to regenerate when the container engine is available.

package openapi

import (
	"encoding/json"
)

// checks if the RoleBindingPatchRequest type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &RoleBindingPatchRequest{}

// RoleBindingPatchRequest struct for RoleBindingPatchRequest
type RoleBindingPatchRequest struct {
	RoleId       *string `json:"role_id,omitempty"`
	Scope        *string `json:"scope,omitempty"`
	UserId       *string `json:"user_id,omitempty"`
	ProjectId    *string `json:"project_id,omitempty"`
	AgentId      *string `json:"agent_id,omitempty"`
	SessionId    *string `json:"session_id,omitempty"`
	CredentialId *string `json:"credential_id,omitempty"`
}

// NewRoleBindingPatchRequest instantiates a new RoleBindingPatchRequest object
func NewRoleBindingPatchRequest() *RoleBindingPatchRequest {
	this := RoleBindingPatchRequest{}
	return &this
}

// NewRoleBindingPatchRequestWithDefaults instantiates a new RoleBindingPatchRequest object with defaults
func NewRoleBindingPatchRequestWithDefaults() *RoleBindingPatchRequest {
	this := RoleBindingPatchRequest{}
	return &this
}

func (o *RoleBindingPatchRequest) GetRoleId() string {
	if o == nil || IsNil(o.RoleId) {
		var ret string
		return ret
	}
	return *o.RoleId
}

func (o *RoleBindingPatchRequest) GetRoleIdOk() (*string, bool) {
	if o == nil || IsNil(o.RoleId) {
		return nil, false
	}
	return o.RoleId, true
}

func (o *RoleBindingPatchRequest) HasRoleId() bool {
	return o != nil && !IsNil(o.RoleId)
}

func (o *RoleBindingPatchRequest) SetRoleId(v string) {
	o.RoleId = &v
}

func (o *RoleBindingPatchRequest) GetScope() string {
	if o == nil || IsNil(o.Scope) {
		var ret string
		return ret
	}
	return *o.Scope
}

func (o *RoleBindingPatchRequest) GetScopeOk() (*string, bool) {
	if o == nil || IsNil(o.Scope) {
		return nil, false
	}
	return o.Scope, true
}

func (o *RoleBindingPatchRequest) HasScope() bool {
	return o != nil && !IsNil(o.Scope)
}

func (o *RoleBindingPatchRequest) SetScope(v string) {
	o.Scope = &v
}

func (o *RoleBindingPatchRequest) GetUserId() string {
	if o == nil || IsNil(o.UserId) {
		var ret string
		return ret
	}
	return *o.UserId
}

func (o *RoleBindingPatchRequest) GetUserIdOk() (*string, bool) {
	if o == nil || IsNil(o.UserId) {
		return nil, false
	}
	return o.UserId, true
}

func (o *RoleBindingPatchRequest) HasUserId() bool {
	return o != nil && !IsNil(o.UserId)
}

func (o *RoleBindingPatchRequest) SetUserId(v string) {
	o.UserId = &v
}

func (o *RoleBindingPatchRequest) GetProjectId() string {
	if o == nil || IsNil(o.ProjectId) {
		var ret string
		return ret
	}
	return *o.ProjectId
}

func (o *RoleBindingPatchRequest) GetProjectIdOk() (*string, bool) {
	if o == nil || IsNil(o.ProjectId) {
		return nil, false
	}
	return o.ProjectId, true
}

func (o *RoleBindingPatchRequest) HasProjectId() bool {
	return o != nil && !IsNil(o.ProjectId)
}

func (o *RoleBindingPatchRequest) SetProjectId(v string) {
	o.ProjectId = &v
}

func (o *RoleBindingPatchRequest) GetAgentId() string {
	if o == nil || IsNil(o.AgentId) {
		var ret string
		return ret
	}
	return *o.AgentId
}

func (o *RoleBindingPatchRequest) GetAgentIdOk() (*string, bool) {
	if o == nil || IsNil(o.AgentId) {
		return nil, false
	}
	return o.AgentId, true
}

func (o *RoleBindingPatchRequest) HasAgentId() bool {
	return o != nil && !IsNil(o.AgentId)
}

func (o *RoleBindingPatchRequest) SetAgentId(v string) {
	o.AgentId = &v
}

func (o *RoleBindingPatchRequest) GetSessionId() string {
	if o == nil || IsNil(o.SessionId) {
		var ret string
		return ret
	}
	return *o.SessionId
}

func (o *RoleBindingPatchRequest) GetSessionIdOk() (*string, bool) {
	if o == nil || IsNil(o.SessionId) {
		return nil, false
	}
	return o.SessionId, true
}

func (o *RoleBindingPatchRequest) HasSessionId() bool {
	return o != nil && !IsNil(o.SessionId)
}

func (o *RoleBindingPatchRequest) SetSessionId(v string) {
	o.SessionId = &v
}

func (o *RoleBindingPatchRequest) GetCredentialId() string {
	if o == nil || IsNil(o.CredentialId) {
		var ret string
		return ret
	}
	return *o.CredentialId
}

func (o *RoleBindingPatchRequest) GetCredentialIdOk() (*string, bool) {
	if o == nil || IsNil(o.CredentialId) {
		return nil, false
	}
	return o.CredentialId, true
}

func (o *RoleBindingPatchRequest) HasCredentialId() bool {
	return o != nil && !IsNil(o.CredentialId)
}

func (o *RoleBindingPatchRequest) SetCredentialId(v string) {
	o.CredentialId = &v
}

func (o RoleBindingPatchRequest) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o RoleBindingPatchRequest) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.RoleId) {
		toSerialize["role_id"] = o.RoleId
	}
	if !IsNil(o.Scope) {
		toSerialize["scope"] = o.Scope
	}
	if !IsNil(o.UserId) {
		toSerialize["user_id"] = o.UserId
	}
	if !IsNil(o.ProjectId) {
		toSerialize["project_id"] = o.ProjectId
	}
	if !IsNil(o.AgentId) {
		toSerialize["agent_id"] = o.AgentId
	}
	if !IsNil(o.SessionId) {
		toSerialize["session_id"] = o.SessionId
	}
	if !IsNil(o.CredentialId) {
		toSerialize["credential_id"] = o.CredentialId
	}
	return toSerialize, nil
}

type NullableRoleBindingPatchRequest struct {
	value *RoleBindingPatchRequest
	isSet bool
}

func (v NullableRoleBindingPatchRequest) Get() *RoleBindingPatchRequest {
	return v.value
}

func (v *NullableRoleBindingPatchRequest) Set(val *RoleBindingPatchRequest) {
	v.value = val
	v.isSet = true
}

func (v NullableRoleBindingPatchRequest) IsSet() bool {
	return v.isSet
}

func (v *NullableRoleBindingPatchRequest) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableRoleBindingPatchRequest(val *RoleBindingPatchRequest) *NullableRoleBindingPatchRequest {
	return &NullableRoleBindingPatchRequest{value: val, isSet: true}
}

func (v NullableRoleBindingPatchRequest) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableRoleBindingPatchRequest) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
