/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"encoding/json"
)

// checks if the SandboxTemplate type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &SandboxTemplate{}

// SandboxTemplate struct for SandboxTemplate
type SandboxTemplate struct {
	// OCI container image reference for the sandbox.
	Image     *string               `json:"image,omitempty"`
	Resources *ResourceRequirements `json:"resources,omitempty"`
	Gpu       *GpuRequirements      `json:"gpu,omitempty"`
	// Kubernetes RuntimeClassName for the sandbox pod.
	RuntimeClassName *string `json:"runtime_class_name,omitempty"`
	// OpenShell driver-specific opaque configuration (JSON).
	DriverConfig map[string]interface{} `json:"driver_config,omitempty"`
	// Labels applied to the sandbox compute resources.
	Labels *map[string]string `json:"labels,omitempty"`
	// Annotations applied to the sandbox compute resources.
	Annotations *map[string]string `json:"annotations,omitempty"`
	// Sandbox supervisor log verbosity (debug, info, warn, error).
	LogLevel *string `json:"log_level,omitempty"`
}

// NewSandboxTemplate instantiates a new SandboxTemplate object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewSandboxTemplate() *SandboxTemplate {
	this := SandboxTemplate{}
	return &this
}

// NewSandboxTemplateWithDefaults instantiates a new SandboxTemplate object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewSandboxTemplateWithDefaults() *SandboxTemplate {
	this := SandboxTemplate{}
	return &this
}

// GetImage returns the Image field value if set, zero value otherwise.
func (o *SandboxTemplate) GetImage() string {
	if o == nil || IsNil(o.Image) {
		var ret string
		return ret
	}
	return *o.Image
}

// GetImageOk returns a tuple with the Image field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxTemplate) GetImageOk() (*string, bool) {
	if o == nil || IsNil(o.Image) {
		return nil, false
	}
	return o.Image, true
}

// HasImage returns a boolean if a field has been set.
func (o *SandboxTemplate) HasImage() bool {
	if o != nil && !IsNil(o.Image) {
		return true
	}

	return false
}

// SetImage gets a reference to the given string and assigns it to the Image field.
func (o *SandboxTemplate) SetImage(v string) {
	o.Image = &v
}

// GetResources returns the Resources field value if set, zero value otherwise.
func (o *SandboxTemplate) GetResources() ResourceRequirements {
	if o == nil || IsNil(o.Resources) {
		var ret ResourceRequirements
		return ret
	}
	return *o.Resources
}

// GetResourcesOk returns a tuple with the Resources field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxTemplate) GetResourcesOk() (*ResourceRequirements, bool) {
	if o == nil || IsNil(o.Resources) {
		return nil, false
	}
	return o.Resources, true
}

// HasResources returns a boolean if a field has been set.
func (o *SandboxTemplate) HasResources() bool {
	if o != nil && !IsNil(o.Resources) {
		return true
	}

	return false
}

// SetResources gets a reference to the given ResourceRequirements and assigns it to the Resources field.
func (o *SandboxTemplate) SetResources(v ResourceRequirements) {
	o.Resources = &v
}

// GetGpu returns the Gpu field value if set, zero value otherwise.
func (o *SandboxTemplate) GetGpu() GpuRequirements {
	if o == nil || IsNil(o.Gpu) {
		var ret GpuRequirements
		return ret
	}
	return *o.Gpu
}

// GetGpuOk returns a tuple with the Gpu field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxTemplate) GetGpuOk() (*GpuRequirements, bool) {
	if o == nil || IsNil(o.Gpu) {
		return nil, false
	}
	return o.Gpu, true
}

// HasGpu returns a boolean if a field has been set.
func (o *SandboxTemplate) HasGpu() bool {
	if o != nil && !IsNil(o.Gpu) {
		return true
	}

	return false
}

// SetGpu gets a reference to the given GpuRequirements and assigns it to the Gpu field.
func (o *SandboxTemplate) SetGpu(v GpuRequirements) {
	o.Gpu = &v
}

// GetRuntimeClassName returns the RuntimeClassName field value if set, zero value otherwise.
func (o *SandboxTemplate) GetRuntimeClassName() string {
	if o == nil || IsNil(o.RuntimeClassName) {
		var ret string
		return ret
	}
	return *o.RuntimeClassName
}

// GetRuntimeClassNameOk returns a tuple with the RuntimeClassName field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxTemplate) GetRuntimeClassNameOk() (*string, bool) {
	if o == nil || IsNil(o.RuntimeClassName) {
		return nil, false
	}
	return o.RuntimeClassName, true
}

// HasRuntimeClassName returns a boolean if a field has been set.
func (o *SandboxTemplate) HasRuntimeClassName() bool {
	if o != nil && !IsNil(o.RuntimeClassName) {
		return true
	}

	return false
}

// SetRuntimeClassName gets a reference to the given string and assigns it to the RuntimeClassName field.
func (o *SandboxTemplate) SetRuntimeClassName(v string) {
	o.RuntimeClassName = &v
}

// GetDriverConfig returns the DriverConfig field value if set, zero value otherwise.
func (o *SandboxTemplate) GetDriverConfig() map[string]interface{} {
	if o == nil || IsNil(o.DriverConfig) {
		var ret map[string]interface{}
		return ret
	}
	return o.DriverConfig
}

// GetDriverConfigOk returns a tuple with the DriverConfig field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxTemplate) GetDriverConfigOk() (map[string]interface{}, bool) {
	if o == nil || IsNil(o.DriverConfig) {
		return map[string]interface{}{}, false
	}
	return o.DriverConfig, true
}

// HasDriverConfig returns a boolean if a field has been set.
func (o *SandboxTemplate) HasDriverConfig() bool {
	if o != nil && !IsNil(o.DriverConfig) {
		return true
	}

	return false
}

// SetDriverConfig gets a reference to the given map[string]interface{} and assigns it to the DriverConfig field.
func (o *SandboxTemplate) SetDriverConfig(v map[string]interface{}) {
	o.DriverConfig = v
}

// GetLabels returns the Labels field value if set, zero value otherwise.
func (o *SandboxTemplate) GetLabels() map[string]string {
	if o == nil || IsNil(o.Labels) {
		var ret map[string]string
		return ret
	}
	return *o.Labels
}

// GetLabelsOk returns a tuple with the Labels field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxTemplate) GetLabelsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Labels) {
		return nil, false
	}
	return o.Labels, true
}

// HasLabels returns a boolean if a field has been set.
func (o *SandboxTemplate) HasLabels() bool {
	if o != nil && !IsNil(o.Labels) {
		return true
	}

	return false
}

// SetLabels gets a reference to the given map[string]string and assigns it to the Labels field.
func (o *SandboxTemplate) SetLabels(v map[string]string) {
	o.Labels = &v
}

// GetAnnotations returns the Annotations field value if set, zero value otherwise.
func (o *SandboxTemplate) GetAnnotations() map[string]string {
	if o == nil || IsNil(o.Annotations) {
		var ret map[string]string
		return ret
	}
	return *o.Annotations
}

// GetAnnotationsOk returns a tuple with the Annotations field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxTemplate) GetAnnotationsOk() (*map[string]string, bool) {
	if o == nil || IsNil(o.Annotations) {
		return nil, false
	}
	return o.Annotations, true
}

// HasAnnotations returns a boolean if a field has been set.
func (o *SandboxTemplate) HasAnnotations() bool {
	if o != nil && !IsNil(o.Annotations) {
		return true
	}

	return false
}

// SetAnnotations gets a reference to the given map[string]string and assigns it to the Annotations field.
func (o *SandboxTemplate) SetAnnotations(v map[string]string) {
	o.Annotations = &v
}

// GetLogLevel returns the LogLevel field value if set, zero value otherwise.
func (o *SandboxTemplate) GetLogLevel() string {
	if o == nil || IsNil(o.LogLevel) {
		var ret string
		return ret
	}
	return *o.LogLevel
}

// GetLogLevelOk returns a tuple with the LogLevel field value if set, nil otherwise
// and a boolean to check if the value has been set.
func (o *SandboxTemplate) GetLogLevelOk() (*string, bool) {
	if o == nil || IsNil(o.LogLevel) {
		return nil, false
	}
	return o.LogLevel, true
}

// HasLogLevel returns a boolean if a field has been set.
func (o *SandboxTemplate) HasLogLevel() bool {
	if o != nil && !IsNil(o.LogLevel) {
		return true
	}

	return false
}

// SetLogLevel gets a reference to the given string and assigns it to the LogLevel field.
func (o *SandboxTemplate) SetLogLevel(v string) {
	o.LogLevel = &v
}

func (o SandboxTemplate) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o SandboxTemplate) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	if !IsNil(o.Image) {
		toSerialize["image"] = o.Image
	}
	if !IsNil(o.Resources) {
		toSerialize["resources"] = o.Resources
	}
	if !IsNil(o.Gpu) {
		toSerialize["gpu"] = o.Gpu
	}
	if !IsNil(o.RuntimeClassName) {
		toSerialize["runtime_class_name"] = o.RuntimeClassName
	}
	if !IsNil(o.DriverConfig) {
		toSerialize["driver_config"] = o.DriverConfig
	}
	if !IsNil(o.Labels) {
		toSerialize["labels"] = o.Labels
	}
	if !IsNil(o.Annotations) {
		toSerialize["annotations"] = o.Annotations
	}
	if !IsNil(o.LogLevel) {
		toSerialize["log_level"] = o.LogLevel
	}
	return toSerialize, nil
}

type NullableSandboxTemplate struct {
	value *SandboxTemplate
	isSet bool
}

func (v NullableSandboxTemplate) Get() *SandboxTemplate {
	return v.value
}

func (v *NullableSandboxTemplate) Set(val *SandboxTemplate) {
	v.value = val
	v.isSet = true
}

func (v NullableSandboxTemplate) IsSet() bool {
	return v.isSet
}

func (v *NullableSandboxTemplate) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullableSandboxTemplate(val *SandboxTemplate) *NullableSandboxTemplate {
	return &NullableSandboxTemplate{value: val, isSet: true}
}

func (v NullableSandboxTemplate) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullableSandboxTemplate) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
