/*
Ambient API Server

Ambient API Server

API version: 1.0.0
Contact: ambient-code@redhat.com
*/

// Code generated by OpenAPI Generator (https://openapi-generator.tech); DO NOT EDIT.

package openapi

import (
	"bytes"
	"encoding/json"
	"fmt"
)

// checks if the PolicyList type satisfies the MappedNullable interface at compile time
var _ MappedNullable = &PolicyList{}

// PolicyList struct for PolicyList
type PolicyList struct {
	Kind  string   `json:"kind"`
	Page  int32    `json:"page"`
	Size  int32    `json:"size"`
	Total int32    `json:"total"`
	Items []Policy `json:"items"`
}

type _PolicyList PolicyList

// NewPolicyList instantiates a new PolicyList object
// This constructor will assign default values to properties that have it defined,
// and makes sure properties required by API are set, but the set of arguments
// will change when the set of required properties is changed
func NewPolicyList(kind string, page int32, size int32, total int32, items []Policy) *PolicyList {
	this := PolicyList{}
	this.Kind = kind
	this.Page = page
	this.Size = size
	this.Total = total
	this.Items = items
	return &this
}

// NewPolicyListWithDefaults instantiates a new PolicyList object
// This constructor will only assign default values to properties that have it defined,
// but it doesn't guarantee that properties required by API are set
func NewPolicyListWithDefaults() *PolicyList {
	this := PolicyList{}
	return &this
}

// GetKind returns the Kind field value
func (o *PolicyList) GetKind() string {
	if o == nil {
		var ret string
		return ret
	}

	return o.Kind
}

// GetKindOk returns a tuple with the Kind field value
// and a boolean to check if the value has been set.
func (o *PolicyList) GetKindOk() (*string, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Kind, true
}

// SetKind sets field value
func (o *PolicyList) SetKind(v string) {
	o.Kind = v
}

// GetPage returns the Page field value
func (o *PolicyList) GetPage() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Page
}

// GetPageOk returns a tuple with the Page field value
// and a boolean to check if the value has been set.
func (o *PolicyList) GetPageOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Page, true
}

// SetPage sets field value
func (o *PolicyList) SetPage(v int32) {
	o.Page = v
}

// GetSize returns the Size field value
func (o *PolicyList) GetSize() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Size
}

// GetSizeOk returns a tuple with the Size field value
// and a boolean to check if the value has been set.
func (o *PolicyList) GetSizeOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Size, true
}

// SetSize sets field value
func (o *PolicyList) SetSize(v int32) {
	o.Size = v
}

// GetTotal returns the Total field value
func (o *PolicyList) GetTotal() int32 {
	if o == nil {
		var ret int32
		return ret
	}

	return o.Total
}

// GetTotalOk returns a tuple with the Total field value
// and a boolean to check if the value has been set.
func (o *PolicyList) GetTotalOk() (*int32, bool) {
	if o == nil {
		return nil, false
	}
	return &o.Total, true
}

// SetTotal sets field value
func (o *PolicyList) SetTotal(v int32) {
	o.Total = v
}

// GetItems returns the Items field value
func (o *PolicyList) GetItems() []Policy {
	if o == nil {
		var ret []Policy
		return ret
	}

	return o.Items
}

// GetItemsOk returns a tuple with the Items field value
// and a boolean to check if the value has been set.
func (o *PolicyList) GetItemsOk() ([]Policy, bool) {
	if o == nil {
		return nil, false
	}
	return o.Items, true
}

// SetItems sets field value
func (o *PolicyList) SetItems(v []Policy) {
	o.Items = v
}

func (o PolicyList) MarshalJSON() ([]byte, error) {
	toSerialize, err := o.ToMap()
	if err != nil {
		return []byte{}, err
	}
	return json.Marshal(toSerialize)
}

func (o PolicyList) ToMap() (map[string]interface{}, error) {
	toSerialize := map[string]interface{}{}
	toSerialize["kind"] = o.Kind
	toSerialize["page"] = o.Page
	toSerialize["size"] = o.Size
	toSerialize["total"] = o.Total
	toSerialize["items"] = o.Items
	return toSerialize, nil
}

func (o *PolicyList) UnmarshalJSON(data []byte) (err error) {
	// This validates that all required properties are included in the JSON object
	// by unmarshalling the object into a generic map with string keys and checking
	// that every required field exists as a key in the generic map.
	requiredProperties := []string{
		"kind",
		"page",
		"size",
		"total",
		"items",
	}

	allProperties := make(map[string]interface{})

	err = json.Unmarshal(data, &allProperties)

	if err != nil {
		return err
	}

	for _, requiredProperty := range requiredProperties {
		if _, exists := allProperties[requiredProperty]; !exists {
			return fmt.Errorf("no value given for required property %v", requiredProperty)
		}
	}

	varPolicyList := _PolicyList{}

	decoder := json.NewDecoder(bytes.NewReader(data))
	decoder.DisallowUnknownFields()
	err = decoder.Decode(&varPolicyList)

	if err != nil {
		return err
	}

	*o = PolicyList(varPolicyList)

	return err
}

type NullablePolicyList struct {
	value *PolicyList
	isSet bool
}

func (v NullablePolicyList) Get() *PolicyList {
	return v.value
}

func (v *NullablePolicyList) Set(val *PolicyList) {
	v.value = val
	v.isSet = true
}

func (v NullablePolicyList) IsSet() bool {
	return v.isSet
}

func (v *NullablePolicyList) Unset() {
	v.value = nil
	v.isSet = false
}

func NewNullablePolicyList(val *PolicyList) *NullablePolicyList {
	return &NullablePolicyList{value: val, isSet: true}
}

func (v NullablePolicyList) MarshalJSON() ([]byte, error) {
	return json.Marshal(v.value)
}

func (v *NullablePolicyList) UnmarshalJSON(src []byte) error {
	v.isSet = true
	return json.Unmarshal(src, &v.value)
}
