// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: da9fbb26cd926e7df1af31ad78f47d005fd328228df521e9e3411636e5069455
// Generated: 2026-05-13T23:03:22Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Agent, AgentList, AgentCreateRequest, AgentPatchRequest } from './agent';

export class AgentAPI {
  constructor(private readonly config: AmbientClientConfig) {}
  private basePath(): string {
    if (!this.config.project) {
      throw new Error('project is required for Agent operations');
    }
    return '/projects/{id}/agents'.replace('{id}', encodeURIComponent(this.config.project));
  }


  async create(data: AgentCreateRequest, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'POST', this.basePath(), data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'GET', `${this.basePath()}/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<AgentList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<AgentList>(this.config, 'GET', `${this.basePath()}${qs}`, undefined, opts);
  }
  async update(id: string, patch: AgentPatchRequest, opts?: RequestOptions): Promise<Agent> {
    return ambientFetch<Agent>(this.config, 'PATCH', `${this.basePath()}/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `${this.basePath()}/${id}`, undefined, opts);
  }

  async start(id: string, opts?: RequestOptions): Promise<Record<string, unknown>> {
    return ambientFetch<Record<string, unknown>>(this.config, 'POST', `${this.basePath()}/${id}/start`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Agent> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
