// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: c0552a0db4fdb51e6e5cf28c453ea87920416eaa69cdca8a78e6063c513b7bab
// Generated: 2026-07-20T04:51:09Z

import type { ObjectReference, ListMeta } from './base';

export type Application = ObjectReference & {
  annotations: string;
  auto_prune: boolean;
  auto_sync: boolean;
  conditions: string;
  credential_id: string;
  destination_ambient_url: string;
  destination_project: string;
  health_status: string;
  labels: string;
  last_synced_at: string;
  name: string;
  operation_message: string;
  operation_phase: string;
  resource_status: string;
  retry_limit: number;
  self_heal: boolean;
  source_path: string;
  source_repo_url: string;
  source_target_revision: string;
  sync_options: string;
  sync_revision: string;
  sync_status: string;
};

export type ApplicationList = ListMeta & {
  items: Application[];
};

export type ApplicationCreateRequest = {
  annotations?: string;
  auto_prune?: boolean;
  auto_sync?: boolean;
  credential_id?: string;
  destination_ambient_url?: string;
  destination_project: string;
  labels?: string;
  name: string;
  retry_limit?: number;
  self_heal?: boolean;
  source_path: string;
  source_repo_url: string;
  source_target_revision?: string;
  sync_options?: string;
};

export type ApplicationPatchRequest = {
  annotations?: string;
  auto_prune?: boolean;
  auto_sync?: boolean;
  credential_id?: string;
  destination_ambient_url?: string;
  destination_project?: string;
  labels?: string;
  name?: string;
  retry_limit?: number;
  self_heal?: boolean;
  source_path?: string;
  source_repo_url?: string;
  source_target_revision?: string;
  sync_options?: string;
};

export class ApplicationBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  autoPrune(value: boolean): this {
    this.data['auto_prune'] = value;
    return this;
  }

  autoSync(value: boolean): this {
    this.data['auto_sync'] = value;
    return this;
  }

  credentialId(value: string): this {
    this.data['credential_id'] = value;
    return this;
  }

  destinationAmbientUrl(value: string): this {
    this.data['destination_ambient_url'] = value;
    return this;
  }

  destinationProject(value: string): this {
    this.data['destination_project'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  retryLimit(value: number): this {
    this.data['retry_limit'] = value;
    return this;
  }

  selfHeal(value: boolean): this {
    this.data['self_heal'] = value;
    return this;
  }

  sourcePath(value: string): this {
    this.data['source_path'] = value;
    return this;
  }

  sourceRepoUrl(value: string): this {
    this.data['source_repo_url'] = value;
    return this;
  }

  sourceTargetRevision(value: string): this {
    this.data['source_target_revision'] = value;
    return this;
  }

  syncOptions(value: string): this {
    this.data['sync_options'] = value;
    return this;
  }

  build(): ApplicationCreateRequest {
    if (!this.data['destination_project']) {
      throw new Error('destination_project is required');
    }
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['source_path']) {
      throw new Error('source_path is required');
    }
    if (!this.data['source_repo_url']) {
      throw new Error('source_repo_url is required');
    }
    return this.data as ApplicationCreateRequest;
  }
}

export class ApplicationPatchBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  autoPrune(value: boolean): this {
    this.data['auto_prune'] = value;
    return this;
  }

  autoSync(value: boolean): this {
    this.data['auto_sync'] = value;
    return this;
  }

  credentialId(value: string): this {
    this.data['credential_id'] = value;
    return this;
  }

  destinationAmbientUrl(value: string): this {
    this.data['destination_ambient_url'] = value;
    return this;
  }

  destinationProject(value: string): this {
    this.data['destination_project'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  retryLimit(value: number): this {
    this.data['retry_limit'] = value;
    return this;
  }

  selfHeal(value: boolean): this {
    this.data['self_heal'] = value;
    return this;
  }

  sourcePath(value: string): this {
    this.data['source_path'] = value;
    return this;
  }

  sourceRepoUrl(value: string): this {
    this.data['source_repo_url'] = value;
    return this;
  }

  sourceTargetRevision(value: string): this {
    this.data['source_target_revision'] = value;
    return this;
  }

  syncOptions(value: string): this {
    this.data['sync_options'] = value;
    return this;
  }

  build(): ApplicationPatchRequest {
    return this.data as ApplicationPatchRequest;
  }
}
