// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: bef3ff7d01cca0bab82f7c3ab91c59e2aceaf2971b9a3a784292ce7d47faa67f
// Generated: 2026-07-19T01:32:48Z

import type { ObjectReference, ListMeta } from './base';

export type Cluster = ObjectReference & {
  annotations: string;
  api_server_url: string;
  capacity: string;
  credential_id: string;
  description: string;
  labels: string;
  last_heartbeat_at: string;
  name: string;
  role: string;
  status: string;
  status_message: string;
};

export type ClusterList = ListMeta & {
  items: Cluster[];
};

export type ClusterCreateRequest = {
  annotations?: string;
  api_server_url: string;
  credential_id?: string;
  description?: string;
  labels?: string;
  name: string;
  role: string;
};

export type ClusterPatchRequest = {
  annotations?: string;
  api_server_url?: string;
  credential_id?: string;
  description?: string;
  labels?: string;
  name?: string;
  role?: string;
};

export class ClusterBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  apiServerUrl(value: string): this {
    this.data['api_server_url'] = value;
    return this;
  }

  credentialId(value: string): this {
    this.data['credential_id'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  role(value: string): this {
    this.data['role'] = value;
    return this;
  }

  build(): ClusterCreateRequest {
    if (!this.data['api_server_url']) {
      throw new Error('api_server_url is required');
    }
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['role']) {
      throw new Error('role is required');
    }
    return this.data as ClusterCreateRequest;
  }
}

export class ClusterPatchBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  apiServerUrl(value: string): this {
    this.data['api_server_url'] = value;
    return this;
  }

  credentialId(value: string): this {
    this.data['credential_id'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  role(value: string): this {
    this.data['role'] = value;
    return this;
  }

  build(): ClusterPatchRequest {
    return this.data as ClusterPatchRequest;
  }
}

export type ClusterStatusResponse = {
  capacity: string;
  id: string;
  last_heartbeat_at: string;
  status: string;
  status_message: string;
};
