// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 84c6a5120d178ae5bb13cd53f756c9ec09c9127f381cf380f9bfc8f8d5de4412
// Generated: 2026-07-15T03:32:32Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Gateway, GatewayList, GatewayCreateRequest, GatewayPatchRequest } from './gateway';

export class GatewayAPI {
  constructor(private readonly config: AmbientClientConfig) {}
  private basePath(): string {
    if (!this.config.project) {
      throw new Error('project is required for Gateway operations');
    }
    return '/projects/{id}/gateways'.replace('{id}', encodeURIComponent(this.config.project));
  }


  async create(data: GatewayCreateRequest, opts?: RequestOptions): Promise<Gateway> {
    return ambientFetch<Gateway>(this.config, 'POST', this.basePath(), data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Gateway> {
    return ambientFetch<Gateway>(this.config, 'GET', `${this.basePath()}/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<GatewayList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<GatewayList>(this.config, 'GET', `${this.basePath()}${qs}`, undefined, opts);
  }
  async update(id: string, patch: GatewayPatchRequest, opts?: RequestOptions): Promise<Gateway> {
    return ambientFetch<Gateway>(this.config, 'PATCH', `${this.basePath()}/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `${this.basePath()}/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Gateway> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
