// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: da9fbb26cd926e7df1af31ad78f47d005fd328228df521e9e3411636e5069455
// Generated: 2026-05-13T23:03:22Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { InboxMessage, InboxMessageList, InboxMessageCreateRequest, InboxMessagePatchRequest } from './inbox_message';

export class InboxMessageAPI {
  constructor(private readonly config: AmbientClientConfig) {}
  private basePath(): string {
    if (!this.config.project) {
      throw new Error('project is required for InboxMessage operations');
    }
    return '/projects/{id}/agents/{agent_id}/inbox'.replace('{id}', encodeURIComponent(this.config.project));
  }


  async create(data: InboxMessageCreateRequest, opts?: RequestOptions): Promise<InboxMessage> {
    return ambientFetch<InboxMessage>(this.config, 'POST', this.basePath(), data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<InboxMessage> {
    return ambientFetch<InboxMessage>(this.config, 'GET', `${this.basePath()}/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<InboxMessageList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<InboxMessageList>(this.config, 'GET', `${this.basePath()}${qs}`, undefined, opts);
  }
  async update(id: string, patch: InboxMessagePatchRequest, opts?: RequestOptions): Promise<InboxMessage> {
    return ambientFetch<InboxMessage>(this.config, 'PATCH', `${this.basePath()}/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `${this.basePath()}/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<InboxMessage> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
