// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: bef3ff7d01cca0bab82f7c3ab91c59e2aceaf2971b9a3a784292ce7d47faa67f
// Generated: 2026-07-19T01:32:48Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Policy, PolicyList, PolicyCreateRequest, PolicyPatchRequest } from './policy';

export class PolicyAPI {
  constructor(private readonly config: AmbientClientConfig) {}
  private basePath(): string {
    if (!this.config.project) {
      throw new Error('project is required for Policy operations');
    }
    return '/projects/{id}/policies'.replace('{id}', encodeURIComponent(this.config.project));
  }


  async create(data: PolicyCreateRequest, opts?: RequestOptions): Promise<Policy> {
    return ambientFetch<Policy>(this.config, 'POST', this.basePath(), data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Policy> {
    return ambientFetch<Policy>(this.config, 'GET', `${this.basePath()}/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<PolicyList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<PolicyList>(this.config, 'GET', `${this.basePath()}${qs}`, undefined, opts);
  }
  async update(id: string, patch: PolicyPatchRequest, opts?: RequestOptions): Promise<Policy> {
    return ambientFetch<Policy>(this.config, 'PATCH', `${this.basePath()}/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `${this.basePath()}/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Policy> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
