// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 84c6a5120d178ae5bb13cd53f756c9ec09c9127f381cf380f9bfc8f8d5de4412
// Generated: 2026-07-15T03:32:32Z

import type { ObjectReference, ListMeta } from './base';

export type Project = ObjectReference & {
  annotations: string;
  description: string;
  labels: string;
  name: string;
  prompt: string;
  status: string;
};

export type ProjectList = ListMeta & {
  items: Project[];
};

export type ProjectCreateRequest = {
  annotations?: string;
  description?: string;
  labels?: string;
  name: string;
  prompt?: string;
  status?: string;
};

export type ProjectPatchRequest = {
  annotations?: string;
  description?: string;
  labels?: string;
  name?: string;
  prompt?: string;
  status?: string;
};

export class ProjectBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  prompt(value: string): this {
    this.data['prompt'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): ProjectCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    return this.data as ProjectCreateRequest;
  }
}

export class ProjectPatchBuilder {
  private data: Record<string, unknown> = {};


  annotations(value: string): this {
    this.data['annotations'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  labels(value: string): this {
    this.data['labels'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  prompt(value: string): this {
    this.data['prompt'] = value;
    return this;
  }

  status(value: string): this {
    this.data['status'] = value;
    return this;
  }

  build(): ProjectPatchRequest {
    return this.data as ProjectPatchRequest;
  }
}
