// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 0d99d538cf2137af9c98c3b852de4b2c46377626d7f163abfb3af9423cad7afa
// Generated: 2026-07-08T01:48:22Z

import type { AmbientClientConfig, ListOptions, RequestOptions } from './base';
import { ambientFetch, buildQueryString } from './base';
import type { Role, RoleList, RoleCreateRequest, RolePatchRequest } from './role';

export class RoleAPI {
  constructor(private readonly config: AmbientClientConfig) {}

  async create(data: RoleCreateRequest, opts?: RequestOptions): Promise<Role> {
    return ambientFetch<Role>(this.config, 'POST', '/roles', data, opts);
  }

  async get(id: string, opts?: RequestOptions): Promise<Role> {
    return ambientFetch<Role>(this.config, 'GET', `/roles/${id}`, undefined, opts);
  }

  async list(listOpts?: ListOptions, opts?: RequestOptions): Promise<RoleList> {
    const qs = buildQueryString(listOpts);
    return ambientFetch<RoleList>(this.config, 'GET', `/roles${qs}`, undefined, opts);
  }
  async update(id: string, patch: RolePatchRequest, opts?: RequestOptions): Promise<Role> {
    return ambientFetch<Role>(this.config, 'PATCH', `/roles/${id}`, patch, opts);
  }

  async delete(id: string, opts?: RequestOptions): Promise<void> {
    return ambientFetch<void>(this.config, 'DELETE', `/roles/${id}`, undefined, opts);
  }

  async *listAll(size: number = 100, opts?: RequestOptions): AsyncGenerator<Role> {
    let page = 1;
    while (true) {
      const result = await this.list({ page, size }, opts);
      for (const item of result.items) {
        yield item;
      }
      if (page * size >= result.total) {
        break;
      }
      page++;
    }
  }
}
