// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: a45fc06b261cd394c9ceb9817484b3742fa24f7acf8e2adaeb15ea4ec80ec86b
// Generated: 2026-06-17T18:27:02Z

import type { ObjectReference, ListMeta } from './base';

export type ScheduledSession = ObjectReference & {
  agent_id: string;
  description: string;
  enabled: boolean;
  inactivity_timeout: number;
  last_run_at: string;
  name: string;
  next_run_at: string;
  project_id: string;
  runner_type: string;
  schedule: string;
  session_prompt: string;
  stop_on_run_finished: boolean;
  timeout: number;
  timezone: string;
};

export type ScheduledSessionList = ListMeta & {
  items: ScheduledSession[];
};

export type ScheduledSessionCreateRequest = {
  agent_id?: string;
  description?: string;
  enabled?: boolean;
  inactivity_timeout?: number;
  last_run_at?: string;
  name: string;
  next_run_at?: string;
  project_id: string;
  runner_type?: string;
  schedule: string;
  session_prompt?: string;
  stop_on_run_finished?: boolean;
  timeout?: number;
  timezone?: string;
};

export type ScheduledSessionPatchRequest = {
  agent_id?: string;
  description?: string;
  enabled?: boolean;
  inactivity_timeout?: number;
  name?: string;
  runner_type?: string;
  schedule?: string;
  session_prompt?: string;
  stop_on_run_finished?: boolean;
  timeout?: number;
  timezone?: string;
};

export class ScheduledSessionBuilder {
  private data: Record<string, unknown> = {};


  agentId(value: string): this {
    this.data['agent_id'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  enabled(value: boolean): this {
    this.data['enabled'] = value;
    return this;
  }

  inactivityTimeout(value: number): this {
    this.data['inactivity_timeout'] = value;
    return this;
  }

  lastRunAt(value: string): this {
    this.data['last_run_at'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  nextRunAt(value: string): this {
    this.data['next_run_at'] = value;
    return this;
  }

  projectId(value: string): this {
    this.data['project_id'] = value;
    return this;
  }

  runnerType(value: string): this {
    this.data['runner_type'] = value;
    return this;
  }

  schedule(value: string): this {
    this.data['schedule'] = value;
    return this;
  }

  sessionPrompt(value: string): this {
    this.data['session_prompt'] = value;
    return this;
  }

  stopOnRunFinished(value: boolean): this {
    this.data['stop_on_run_finished'] = value;
    return this;
  }

  timeout(value: number): this {
    this.data['timeout'] = value;
    return this;
  }

  timezone(value: string): this {
    this.data['timezone'] = value;
    return this;
  }

  build(): ScheduledSessionCreateRequest {
    if (!this.data['name']) {
      throw new Error('name is required');
    }
    if (!this.data['project_id']) {
      throw new Error('project_id is required');
    }
    if (!this.data['schedule']) {
      throw new Error('schedule is required');
    }
    return this.data as ScheduledSessionCreateRequest;
  }
}

export class ScheduledSessionPatchBuilder {
  private data: Record<string, unknown> = {};


  agentId(value: string): this {
    this.data['agent_id'] = value;
    return this;
  }

  description(value: string): this {
    this.data['description'] = value;
    return this;
  }

  enabled(value: boolean): this {
    this.data['enabled'] = value;
    return this;
  }

  inactivityTimeout(value: number): this {
    this.data['inactivity_timeout'] = value;
    return this;
  }

  name(value: string): this {
    this.data['name'] = value;
    return this;
  }

  runnerType(value: string): this {
    this.data['runner_type'] = value;
    return this;
  }

  schedule(value: string): this {
    this.data['schedule'] = value;
    return this;
  }

  sessionPrompt(value: string): this {
    this.data['session_prompt'] = value;
    return this;
  }

  stopOnRunFinished(value: boolean): this {
    this.data['stop_on_run_finished'] = value;
    return this;
  }

  timeout(value: number): this {
    this.data['timeout'] = value;
    return this;
  }

  timezone(value: string): this {
    this.data['timezone'] = value;
    return this;
  }

  build(): ScheduledSessionPatchRequest {
    return this.data as ScheduledSessionPatchRequest;
  }
}
