// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 84c6a5120d178ae5bb13cd53f756c9ec09c9127f381cf380f9bfc8f8d5de4412
// Generated: 2026-07-15T03:32:32Z

import type { ObjectReference, ListMeta } from './base';

export type SessionEvent = ObjectReference & {
  completed_at?: string;
  event_count: number;
  event_type: string;
  payload: string;
  seq: number;
  session_id: string;
};

export type SessionEventList = ListMeta & {
  items: SessionEvent[];
};

export type SessionEventCreateRequest = {
  event_type?: string;
  payload?: string;
};

export type SessionEventPatchRequest = {
};

export class SessionEventBuilder {
  private data: Record<string, unknown> = {};


  eventType(value: string): this {
    this.data['event_type'] = value;
    return this;
  }

  payload(value: string): this {
    this.data['payload'] = value;
    return this;
  }

  build(): SessionEventCreateRequest {
    return this.data as SessionEventCreateRequest;
  }
}

export class SessionEventPatchBuilder {
  private data: Record<string, unknown> = {};


  build(): SessionEventPatchRequest {
    return this.data as SessionEventPatchRequest;
  }
}
