// Vendored subset of the OpenShell inference proto.
// Source: github.com/nvidia/openshell  proto/inference.proto
// Only SetClusterInference and GetClusterInference are needed for ACP.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: openshell/inference/v1/inference.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetClusterInferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	RouteName     string                 `protobuf:"bytes,3,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	Verify        bool                   `protobuf:"varint,4,opt,name=verify,proto3" json:"verify,omitempty"`
	NoVerify      bool                   `protobuf:"varint,5,opt,name=no_verify,json=noVerify,proto3" json:"no_verify,omitempty"`
	TimeoutSecs   uint64                 `protobuf:"varint,6,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetClusterInferenceRequest) Reset() {
	*x = SetClusterInferenceRequest{}
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClusterInferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClusterInferenceRequest) ProtoMessage() {}

func (x *SetClusterInferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClusterInferenceRequest.ProtoReflect.Descriptor instead.
func (*SetClusterInferenceRequest) Descriptor() ([]byte, []int) {
	return file_openshell_inference_v1_inference_proto_rawDescGZIP(), []int{0}
}

func (x *SetClusterInferenceRequest) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SetClusterInferenceRequest) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SetClusterInferenceRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *SetClusterInferenceRequest) GetVerify() bool {
	if x != nil {
		return x.Verify
	}
	return false
}

func (x *SetClusterInferenceRequest) GetNoVerify() bool {
	if x != nil {
		return x.NoVerify
	}
	return false
}

func (x *SetClusterInferenceRequest) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

type SetClusterInferenceResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ProviderName        string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ModelId             string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version             uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	RouteName           string                 `protobuf:"bytes,4,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	ValidationPerformed bool                   `protobuf:"varint,5,opt,name=validation_performed,json=validationPerformed,proto3" json:"validation_performed,omitempty"`
	TimeoutSecs         uint64                 `protobuf:"varint,7,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *SetClusterInferenceResponse) Reset() {
	*x = SetClusterInferenceResponse{}
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetClusterInferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetClusterInferenceResponse) ProtoMessage() {}

func (x *SetClusterInferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetClusterInferenceResponse.ProtoReflect.Descriptor instead.
func (*SetClusterInferenceResponse) Descriptor() ([]byte, []int) {
	return file_openshell_inference_v1_inference_proto_rawDescGZIP(), []int{1}
}

func (x *SetClusterInferenceResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *SetClusterInferenceResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *SetClusterInferenceResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *SetClusterInferenceResponse) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *SetClusterInferenceResponse) GetValidationPerformed() bool {
	if x != nil {
		return x.ValidationPerformed
	}
	return false
}

func (x *SetClusterInferenceResponse) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

type GetClusterInferenceRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RouteName     string                 `protobuf:"bytes,1,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInferenceRequest) Reset() {
	*x = GetClusterInferenceRequest{}
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInferenceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInferenceRequest) ProtoMessage() {}

func (x *GetClusterInferenceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInferenceRequest.ProtoReflect.Descriptor instead.
func (*GetClusterInferenceRequest) Descriptor() ([]byte, []int) {
	return file_openshell_inference_v1_inference_proto_rawDescGZIP(), []int{2}
}

func (x *GetClusterInferenceRequest) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

type GetClusterInferenceResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProviderName  string                 `protobuf:"bytes,1,opt,name=provider_name,json=providerName,proto3" json:"provider_name,omitempty"`
	ModelId       string                 `protobuf:"bytes,2,opt,name=model_id,json=modelId,proto3" json:"model_id,omitempty"`
	Version       uint64                 `protobuf:"varint,3,opt,name=version,proto3" json:"version,omitempty"`
	RouteName     string                 `protobuf:"bytes,4,opt,name=route_name,json=routeName,proto3" json:"route_name,omitempty"`
	TimeoutSecs   uint64                 `protobuf:"varint,5,opt,name=timeout_secs,json=timeoutSecs,proto3" json:"timeout_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetClusterInferenceResponse) Reset() {
	*x = GetClusterInferenceResponse{}
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetClusterInferenceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetClusterInferenceResponse) ProtoMessage() {}

func (x *GetClusterInferenceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_openshell_inference_v1_inference_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetClusterInferenceResponse.ProtoReflect.Descriptor instead.
func (*GetClusterInferenceResponse) Descriptor() ([]byte, []int) {
	return file_openshell_inference_v1_inference_proto_rawDescGZIP(), []int{3}
}

func (x *GetClusterInferenceResponse) GetProviderName() string {
	if x != nil {
		return x.ProviderName
	}
	return ""
}

func (x *GetClusterInferenceResponse) GetModelId() string {
	if x != nil {
		return x.ModelId
	}
	return ""
}

func (x *GetClusterInferenceResponse) GetVersion() uint64 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetClusterInferenceResponse) GetRouteName() string {
	if x != nil {
		return x.RouteName
	}
	return ""
}

func (x *GetClusterInferenceResponse) GetTimeoutSecs() uint64 {
	if x != nil {
		return x.TimeoutSecs
	}
	return 0
}

var File_openshell_inference_v1_inference_proto protoreflect.FileDescriptor

const file_openshell_inference_v1_inference_proto_rawDesc = "" +
	"\n" +
	"&openshell/inference/v1/inference.proto\x12\x16openshell.inference.v1\"\xd3\x01\n" +
	"\x1aSetClusterInferenceRequest\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x1d\n" +
	"\n" +
	"route_name\x18\x03 \x01(\tR\trouteName\x12\x16\n" +
	"\x06verify\x18\x04 \x01(\bR\x06verify\x12\x1b\n" +
	"\tno_verify\x18\x05 \x01(\bR\bnoVerify\x12!\n" +
	"\ftimeout_secs\x18\x06 \x01(\x04R\vtimeoutSecs\"\xec\x01\n" +
	"\x1bSetClusterInferenceResponse\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"route_name\x18\x04 \x01(\tR\trouteName\x121\n" +
	"\x14validation_performed\x18\x05 \x01(\bR\x13validationPerformed\x12!\n" +
	"\ftimeout_secs\x18\a \x01(\x04R\vtimeoutSecs\";\n" +
	"\x1aGetClusterInferenceRequest\x12\x1d\n" +
	"\n" +
	"route_name\x18\x01 \x01(\tR\trouteName\"\xb9\x01\n" +
	"\x1bGetClusterInferenceResponse\x12#\n" +
	"\rprovider_name\x18\x01 \x01(\tR\fproviderName\x12\x19\n" +
	"\bmodel_id\x18\x02 \x01(\tR\amodelId\x12\x18\n" +
	"\aversion\x18\x03 \x01(\x04R\aversion\x12\x1d\n" +
	"\n" +
	"route_name\x18\x04 \x01(\tR\trouteName\x12!\n" +
	"\ftimeout_secs\x18\x05 \x01(\x04R\vtimeoutSecs2\x8b\x02\n" +
	"\tInference\x12~\n" +
	"\x13SetClusterInference\x122.openshell.inference.v1.SetClusterInferenceRequest\x1a3.openshell.inference.v1.SetClusterInferenceResponse\x12~\n" +
	"\x13GetClusterInference\x122.openshell.inference.v1.GetClusterInferenceRequest\x1a3.openshell.inference.v1.GetClusterInferenceResponseBrZpgithub.com/ambient-code/platform/components/ambient-control-plane/internal/openshell/grpc/openshell/inference/v1b\x06proto3"

var (
	file_openshell_inference_v1_inference_proto_rawDescOnce sync.Once
	file_openshell_inference_v1_inference_proto_rawDescData []byte
)

func file_openshell_inference_v1_inference_proto_rawDescGZIP() []byte {
	file_openshell_inference_v1_inference_proto_rawDescOnce.Do(func() {
		file_openshell_inference_v1_inference_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_openshell_inference_v1_inference_proto_rawDesc), len(file_openshell_inference_v1_inference_proto_rawDesc)))
	})
	return file_openshell_inference_v1_inference_proto_rawDescData
}

var file_openshell_inference_v1_inference_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_openshell_inference_v1_inference_proto_goTypes = []any{
	(*SetClusterInferenceRequest)(nil),  // 0: openshell.inference.v1.SetClusterInferenceRequest
	(*SetClusterInferenceResponse)(nil), // 1: openshell.inference.v1.SetClusterInferenceResponse
	(*GetClusterInferenceRequest)(nil),  // 2: openshell.inference.v1.GetClusterInferenceRequest
	(*GetClusterInferenceResponse)(nil), // 3: openshell.inference.v1.GetClusterInferenceResponse
}
var file_openshell_inference_v1_inference_proto_depIdxs = []int32{
	0, // 0: openshell.inference.v1.Inference.SetClusterInference:input_type -> openshell.inference.v1.SetClusterInferenceRequest
	2, // 1: openshell.inference.v1.Inference.GetClusterInference:input_type -> openshell.inference.v1.GetClusterInferenceRequest
	1, // 2: openshell.inference.v1.Inference.SetClusterInference:output_type -> openshell.inference.v1.SetClusterInferenceResponse
	3, // 3: openshell.inference.v1.Inference.GetClusterInference:output_type -> openshell.inference.v1.GetClusterInferenceResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_openshell_inference_v1_inference_proto_init() }
func file_openshell_inference_v1_inference_proto_init() {
	if File_openshell_inference_v1_inference_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_openshell_inference_v1_inference_proto_rawDesc), len(file_openshell_inference_v1_inference_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_openshell_inference_v1_inference_proto_goTypes,
		DependencyIndexes: file_openshell_inference_v1_inference_proto_depIdxs,
		MessageInfos:      file_openshell_inference_v1_inference_proto_msgTypes,
	}.Build()
	File_openshell_inference_v1_inference_proto = out.File
	file_openshell_inference_v1_inference_proto_goTypes = nil
	file_openshell_inference_v1_inference_proto_depIdxs = nil
}
