// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 0d99d538cf2137af9c98c3b852de4b2c46377626d7f163abfb3af9423cad7afa
// Generated: 2026-07-08T01:48:22Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type CredentialAPI struct {
	client *Client
}

func (c *Client) Credentials() *CredentialAPI {
	return &CredentialAPI{client: c}
}

func (a *CredentialAPI) Create(ctx context.Context, resource *types.Credential) (*types.Credential, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal credential: %w", err)
	}
	var result types.Credential
	if err := a.client.do(ctx, http.MethodPost, "/credentials", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *CredentialAPI) Get(ctx context.Context, id string) (*types.Credential, error) {
	var result types.Credential
	if err := a.client.do(ctx, http.MethodGet, "/credentials/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *CredentialAPI) List(ctx context.Context, opts *types.ListOptions) (*types.CredentialList, error) {
	var result types.CredentialList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/credentials", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *CredentialAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Credential, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Credential
	if err := a.client.do(ctx, http.MethodPatch, "/credentials/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *CredentialAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/credentials/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *CredentialAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Credential] {
	return NewIterator(func(page int) (*types.CredentialList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
