// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: c0552a0db4fdb51e6e5cf28c453ea87920416eaa69cdca8a78e6063c513b7bab
// Generated: 2026-07-20T04:51:09Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type GatewayAPI struct {
	client *Client
}

func (c *Client) Gateways() *GatewayAPI {
	return &GatewayAPI{client: c}
}
func (a *GatewayAPI) basePath() string {
	return strings.NewReplacer("{id}", url.PathEscape(a.client.project)).Replace("/projects/{id}/gateways")
}

func (a *GatewayAPI) Create(ctx context.Context, resource *types.Gateway) (*types.Gateway, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal gateway: %w", err)
	}
	var result types.Gateway
	if err := a.client.do(ctx, http.MethodPost, a.basePath(), body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayAPI) Get(ctx context.Context, id string) (*types.Gateway, error) {
	var result types.Gateway
	if err := a.client.do(ctx, http.MethodGet, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayAPI) List(ctx context.Context, opts *types.ListOptions) (*types.GatewayList, error) {
	var result types.GatewayList
	if err := a.client.doWithQuery(ctx, http.MethodGet, a.basePath(), nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *GatewayAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Gateway, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Gateway
	if err := a.client.do(ctx, http.MethodPatch, a.basePath()+"/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *GatewayAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *GatewayAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Gateway] {
	return NewIterator(func(page int) (*types.GatewayList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
