// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: ed0a896aa0e4678be21149b07fe658b66ddc41e3d4b41b372e8cf6377e8c927e
// Generated: 2026-06-30T15:47:18Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type InboxMessageAPI struct {
	client *Client
}

func (c *Client) InboxMessages() *InboxMessageAPI {
	return &InboxMessageAPI{client: c}
}
func (a *InboxMessageAPI) basePath() string {
	return strings.NewReplacer("{id}", url.PathEscape(a.client.project)).Replace("/projects/{id}/agents/{agent_id}/inbox")
}

func (a *InboxMessageAPI) Create(ctx context.Context, resource *types.InboxMessage) (*types.InboxMessage, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal inbox_message: %w", err)
	}
	var result types.InboxMessage
	if err := a.client.do(ctx, http.MethodPost, a.basePath(), body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *InboxMessageAPI) Get(ctx context.Context, id string) (*types.InboxMessage, error) {
	var result types.InboxMessage
	if err := a.client.do(ctx, http.MethodGet, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *InboxMessageAPI) List(ctx context.Context, opts *types.ListOptions) (*types.InboxMessageList, error) {
	var result types.InboxMessageList
	if err := a.client.doWithQuery(ctx, http.MethodGet, a.basePath(), nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *InboxMessageAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.InboxMessage, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.InboxMessage
	if err := a.client.do(ctx, http.MethodPatch, a.basePath()+"/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *InboxMessageAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *InboxMessageAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.InboxMessage] {
	return NewIterator(func(page int) (*types.InboxMessageList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
