// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: c0552a0db4fdb51e6e5cf28c453ea87920416eaa69cdca8a78e6063c513b7bab
// Generated: 2026-07-20T04:51:09Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ProviderAPI struct {
	client *Client
}

func (c *Client) Providers() *ProviderAPI {
	return &ProviderAPI{client: c}
}
func (a *ProviderAPI) basePath() string {
	return strings.NewReplacer("{id}", url.PathEscape(a.client.project)).Replace("/projects/{id}/providers")
}

func (a *ProviderAPI) Create(ctx context.Context, resource *types.Provider) (*types.Provider, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal provider: %w", err)
	}
	var result types.Provider
	if err := a.client.do(ctx, http.MethodPost, a.basePath(), body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProviderAPI) Get(ctx context.Context, id string) (*types.Provider, error) {
	var result types.Provider
	if err := a.client.do(ctx, http.MethodGet, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProviderAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ProviderList, error) {
	var result types.ProviderList
	if err := a.client.doWithQuery(ctx, http.MethodGet, a.basePath(), nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *ProviderAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Provider, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Provider
	if err := a.client.do(ctx, http.MethodPatch, a.basePath()+"/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ProviderAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *ProviderAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Provider] {
	return NewIterator(func(page int) (*types.ProviderList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
