// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: bef3ff7d01cca0bab82f7c3ab91c59e2aceaf2971b9a3a784292ce7d47faa67f
// Generated: 2026-07-19T01:32:48Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type ScheduledSessionAPI struct {
	client *Client
}

func (c *Client) ScheduledSessions() *ScheduledSessionAPI {
	return &ScheduledSessionAPI{client: c}
}
func (a *ScheduledSessionAPI) basePath() string {
	return strings.NewReplacer("{id}", url.PathEscape(a.client.project)).Replace("/projects/{id}/scheduled-sessions")
}

func (a *ScheduledSessionAPI) Create(ctx context.Context, resource *types.ScheduledSession) (*types.ScheduledSession, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal scheduled_session: %w", err)
	}
	var result types.ScheduledSession
	if err := a.client.do(ctx, http.MethodPost, a.basePath(), body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ScheduledSessionAPI) Get(ctx context.Context, id string) (*types.ScheduledSession, error) {
	var result types.ScheduledSession
	if err := a.client.do(ctx, http.MethodGet, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ScheduledSessionAPI) List(ctx context.Context, opts *types.ListOptions) (*types.ScheduledSessionList, error) {
	var result types.ScheduledSessionList
	if err := a.client.doWithQuery(ctx, http.MethodGet, a.basePath(), nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *ScheduledSessionAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.ScheduledSession, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.ScheduledSession
	if err := a.client.do(ctx, http.MethodPatch, a.basePath()+"/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ScheduledSessionAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *ScheduledSessionAPI) Resume(ctx context.Context, id string) (*types.ScheduledSession, error) {
	var result types.ScheduledSession
	if err := a.client.do(ctx, http.MethodPost, a.basePath()+"/"+url.PathEscape(id)+"/resume", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ScheduledSessionAPI) Runs(ctx context.Context, id string) (*types.SessionList, error) {
	var result types.SessionList
	if err := a.client.do(ctx, http.MethodGet, a.basePath()+"/"+url.PathEscape(id)+"/runs", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ScheduledSessionAPI) Suspend(ctx context.Context, id string) (*types.ScheduledSession, error) {
	var result types.ScheduledSession
	if err := a.client.do(ctx, http.MethodPost, a.basePath()+"/"+url.PathEscape(id)+"/suspend", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ScheduledSessionAPI) Trigger(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodPost, a.basePath()+"/"+url.PathEscape(id)+"/trigger", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *ScheduledSessionAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.ScheduledSession] {
	return NewIterator(func(page int) (*types.ScheduledSessionList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
