// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: 84c6a5120d178ae5bb13cd53f756c9ec09c9127f381cf380f9bfc8f8d5de4412
// Generated: 2026-07-15T03:32:32Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"strings"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type SessionEventAPI struct {
	client *Client
}

func (c *Client) SessionEvents() *SessionEventAPI {
	return &SessionEventAPI{client: c}
}
func (a *SessionEventAPI) basePath() string {
	return strings.NewReplacer("{id}", url.PathEscape(a.client.project)).Replace("/sessions/{id}/events/history")
}

func (a *SessionEventAPI) Create(ctx context.Context, resource *types.SessionEvent) (*types.SessionEvent, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal session_event: %w", err)
	}
	var result types.SessionEvent
	if err := a.client.do(ctx, http.MethodPost, a.basePath(), body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionEventAPI) Get(ctx context.Context, id string) (*types.SessionEvent, error) {
	var result types.SessionEvent
	if err := a.client.do(ctx, http.MethodGet, a.basePath()+"/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionEventAPI) List(ctx context.Context, opts *types.ListOptions) (*types.SessionEventList, error) {
	var result types.SessionEventList
	if err := a.client.doWithQuery(ctx, http.MethodGet, a.basePath(), nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *SessionEventAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.SessionEvent] {
	return NewIterator(func(page int) (*types.SessionEventList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
