// Code generated by ambient-sdk-generator from openapi.yaml — DO NOT EDIT.
// Source: ../../ambient-api-server/openapi/openapi.yaml
// Spec SHA256: bef3ff7d01cca0bab82f7c3ab91c59e2aceaf2971b9a3a784292ce7d47faa67f
// Generated: 2026-07-19T01:32:48Z

package client

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"

	"github.com/ambient-code/platform/components/ambient-sdk/go-sdk/types"
)

type SessionAPI struct {
	client *Client
}

func (c *Client) Sessions() *SessionAPI {
	return &SessionAPI{client: c}
}

func (a *SessionAPI) Create(ctx context.Context, resource *types.Session) (*types.Session, error) {
	body, err := json.Marshal(resource)
	if err != nil {
		return nil, fmt.Errorf("marshal session: %w", err)
	}
	var result types.Session
	if err := a.client.do(ctx, http.MethodPost, "/sessions", body, http.StatusCreated, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Get(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodGet, "/sessions/"+url.PathEscape(id), nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) List(ctx context.Context, opts *types.ListOptions) (*types.SessionList, error) {
	var result types.SessionList
	if err := a.client.doWithQuery(ctx, http.MethodGet, "/sessions", nil, http.StatusOK, &result, opts); err != nil {
		return nil, err
	}
	return &result, nil
}
func (a *SessionAPI) Update(ctx context.Context, id string, patch map[string]any) (*types.Session, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal patch: %w", err)
	}
	var result types.Session
	if err := a.client.do(ctx, http.MethodPatch, "/sessions/"+url.PathEscape(id), body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Delete(ctx context.Context, id string) error {
	return a.client.do(ctx, http.MethodDelete, "/sessions/"+url.PathEscape(id), nil, http.StatusNoContent, nil)
}

func (a *SessionAPI) UpdateStatus(ctx context.Context, id string, patch map[string]any) (*types.Session, error) {
	body, err := json.Marshal(patch)
	if err != nil {
		return nil, fmt.Errorf("marshal status patch: %w", err)
	}
	var result types.Session
	if err := a.client.do(ctx, http.MethodPatch, "/sessions/"+url.PathEscape(id)+"/status", body, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Start(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodPost, "/sessions/"+url.PathEscape(id)+"/start", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Status(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodPatch, "/sessions/"+url.PathEscape(id)+"/status", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) Stop(ctx context.Context, id string) (*types.Session, error) {
	var result types.Session
	if err := a.client.do(ctx, http.MethodPost, "/sessions/"+url.PathEscape(id)+"/stop", nil, http.StatusOK, &result); err != nil {
		return nil, err
	}
	return &result, nil
}

func (a *SessionAPI) ListAll(ctx context.Context, opts *types.ListOptions) *Iterator[types.Session] {
	return NewIterator(func(page int) (*types.SessionList, error) {
		o := *opts
		o.Page = page
		return a.List(ctx, &o)
	})
}
